API images/create added missing parameters platform, message, repo
containers/podman pull request #10548
Opened 2021-06-03 13:52 UTC by cdoern

Signed-off-by: cdoern <cbdoer23@g.holycross.edu>

Added support for the query parameters platform, message, and repo. Also edited documentation and formatted the request string as binary in register_images.go. CreateImageFromSrc within pkg/api/handlers/compat/images.go has some issues with supporting platform due to imageEngine.Import/the ImageImportOptions struct not supporting a platform parameter. 

I will most likely open a separate issue to handle this as it deals more with our side rather than the docker API. You can see [here](https://github.com/docker/engine/blob/7c6a9484ee37b28fa314f716581bdb268cd78ce2/api/server/router/image/image_routes.go#L26) that Docker supports platform in both the fromSrc and fromImage requests.

2021-06-03 15:52 UTC, jwhonce requested changes

2021-06-03 15:52 UTC, jwhonce commented on pkg/api/handlers/compat/images.go
> +		pullOptions.Variant = platformSpecs[2]
Please see cmd/podman/images/pull.go:140 for a safer handling of Platform parsing.

2021-06-03 15:52 UTC, jwhonce commented on test/apiv2/python/rest_api/test_v2_0_0_image.py
> +        r = requests.post(self.uri("/images/create?fromImage=alpine&message=testing123&platform=/linux[/amd64[/v8]]"), timeout=15)
```suggestion
        r = requests.post(self.uri("/images/create?fromImage=alpine&message=testing123&platform=linux/amd64/v8"), timeout=15)
```
The brackets should not be sent.

2021-06-03 21:07 UTC, jwhonce commented on pkg/api/handlers/compat/images.go
> +		pullOptions.Variant = platformSpecs[2]
@cdoern Response from IRC question when using platform, `OS`, `OS/Architecture`, and `OS/Architecture/Variant` are all legal values.

2021-06-03 21:14 UTC, jwhonce requested changes
Tweaks around defaulting to Go's _Zero_ values.

2021-06-03 21:14 UTC, jwhonce commented on pkg/api/handlers/compat/images.go
> +			}
```suggestion
			}
```
The _Zero_ value for strings is `""`.

2021-06-03 21:14 UTC, jwhonce commented on pkg/api/handlers/compat/images.go
> +		}
```suggestion
		} 
```
The Zero value for strings is "".

2021-06-03 21:14 UTC, jwhonce commented on pkg/api/handlers/compat/images.go
> +			}
```suggestion
			}
```

2021-06-04 15:19 UTC, baude commented
/approve

2021-06-07 13:08 UTC, rhatdan commented
LGTM

2021-06-07 13:09 UTC, rhatdan commented
@baude @jwhonce PTAL

2021-06-08 15:43 UTC, jwhonce approved these changes

2021-06-08 15:43 UTC, jwhonce commented
/lgtm

2021-06-08 15:44 UTC, merged