feat(ssh): make debugging ssh show command
containers/podman pull request #10798
Opened 2021-06-28 09:42 UTC by georgettica

in order to use the SSH variables for other uses, expose these args as a string, which can be used elsewhere

I wanted to build a container but I got the error:
```
Error: stat /var/tmp/libpod_builder758690613/build/["Dockerfile"]: no such file or directory
```

so I wanted to copy the docker file and the repo that came with it into the VM
which I was able to do

also I am now stuck on running 
```
podman images
localhost/IMAGE            latest      XXXX  12 minutes ago  XXXX

podman run --rm -it IMAGE bash
Error: Error initializing source docker://localhost/IMAGEr:latest: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
```

I can create an issue if needed

(specs of my machine will be given upon request)
I am using macOS

2021-06-28 12:39 UTC, mheon commented
Any reason why a logrus.Debugf() wouldn’t work?

On Mon, Jun 28, 2021 at 05:43 openshift-ci[bot] ***@***.***>
wrote:

> [APPROVALNOTIFIER] This PR is *NOT APPROVED*
>
> This pull-request has been approved by: *georgettica
> <https://github.com/containers/podman/pull/10798#>*
> To complete the pull request process
> <https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process>,
> please assign *vrothberg* after the PR has been reviewed.
> You can assign the PR to them by writing /assign @vrothberg in a comment
> when ready.
>
> The full list of commands accepted by this bot can be found here
> <https://go.k8s.io/bot-commands?repo=containers%2Fpodman>.
> Needs approval from an approver in each of these files:
>
>    - *OWNERS <https://github.com/containers/podman/blob/master/OWNERS>*
>
> Approvers can indicate their approval by writing /approve in a comment
> Approvers can cancel approval by writing /approve cancel in a comment
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/containers/podman/pull/10798#issuecomment-869537931>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3AOCBCYSPYYQHSQ3VO2LDTVA72HANCNFSM47NTD4SQ>
> .
>

2021-06-28 22:06 UTC, jwhonce requested changes

2021-06-28 22:06 UTC, jwhonce commented on pkg/machine/qemu/machine.go
> +	}
```suggestion
		logrus.Debugf("The arguments passed to ssh are: %v\n", args)
```

2021-07-04 11:43 UTC, georgettica commented
No reason, just copied from somewhere else in the codebase

2021-07-15 11:59 UTC, vrothberg commented
@georgettica, do you want to push this PR forward?

2021-07-17 01:09 UTC, georgettica commented
Sadly no, but I think the feature is a good addition to the tool.

2021-08-04 20:22 UTC, baude commented
ill push it over the finish line.  thanks @georgettica

2021-08-04 20:24 UTC, baude commented
Replaced by #11136

2021-08-04 20:24 UTC, closed without merging