Add tests to verify CORs is enabled
containers/podman pull request #11019
Opened 2021-07-22 11:51 UTC by boaz0

closes #8645 and related to #10546

//cc @rhatdan @edsantiago

2021-07-22 12:27 UTC, rhatdan commented
LGTM if it passes.

2021-07-22 14:11 UTC, mheon commented
@edsantiago Mind doing a quick review on the test?

2021-07-22 14:24 UTC, boaz0 commented
Ummm, I wonder why the service wasn't running :thinking:

2021-07-22 14:35 UTC, edsantiago requested changes
Tests are failing, I don't have time to debug those right now but assume you can easily figure out the problem.

This is nice work, just a few changes requested.

2021-07-22 14:35 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +        local pause_pid="$XDG_RUNTIME_DIR/libpod/tmp/pause.pid"
Could you name this `pause_pid_file` instead? A variable named `pause_pid` makes me think it's the actual PID

2021-07-22 14:35 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +            kill -9 $(cat $pause_pid) 2> /dev/null
Is there any way we can avoid `kill -9`? In fact, is there any way we can do this with podman commands? This sort of unclean knowledge of internals troubles me; and `kill -9` always makes me cringe.

2021-07-22 14:35 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +    result=$(run_podman system service --log-level="debug" --cors=* -t 1 | grep "CORS Headers were set to *")
This does not do what you think it does. You probably want something like this instead:
```bash
    run_podman system service ...
    is "$output" ".*CORS Headers were set to.*" "debug log confirms CORS headers set"
```

2021-07-22 19:52 UTC, edsantiago requested changes
Much cleaner, thank you. Still some blocking concerns though.

2021-07-22 19:52 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +    run_podman system service --cors=* tcp:$SERVICE_TCP_ADDR -t 20 &
Unquoted asterisk is dangerous, please quote it in single quotes: `--cors='*'`

2021-07-22 19:52 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +    kill -9 $podman_pid
Pretty please try to break the habit of using `kill -9`. Change this to:
```
    kill $podman_pid
    wait $podman_pid || true
```

2021-07-22 19:52 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +    run_podman system service --log-level="debug" --cors=* -t 1
Same asterisk comment

2021-07-22 19:52 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +    sleep 5s
`sleep` is a bad idea, but I'll allow it for now because `wait_for_port` is broken (emergency PR in the works)

2021-07-22 19:53 UTC, edsantiago commented
Actually, since you need to resubmit, could I ask you to add a new test, one that confirms that CORS headers are *not* present when run by default? Thanks.

2021-07-22 19:53 UTC, edsantiago commented on test/system/271-tcp-cors-server.bats
> +@test "podman system service - tcp CORS " {
Oh, one more, please remove trailing whitespace

2021-07-23 18:27 UTC, TomSweeneyRedHat commented
LGTM
once @edsantiago 's latest comments are addressed.

2021-07-26 11:54 UTC, edsantiago approved these changes

2021-07-26 11:55 UTC, edsantiago commented
/lgtm

Nice work, @boaz0 . Thank you.

2021-07-26 11:56 UTC, merged

2021-07-26 13:05 UTC, boaz0 commented
### Thanks @edsantiago & @TomSweeneyRedHat & @rhatdan 
![](https://media.giphy.com/media/gjgWQA5QBuBmUZahOP/giphy-downsized.gif)