Fix up build the docs site
containers/podman pull request #11612
Opened 2021-09-16 16:31 UTC by rhatdan

[NO TESTS NEEDED]

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

2021-09-16 16:31 UTC, rhatdan commented
Alternative to https://github.com/containers/podman/pull/11611

2021-09-16 16:32 UTC, rhatdan commented
@TomSweeneyRedHat This will fix up the man pages to show the full podman-machine.1 rather then just the subcommands.

2021-09-16 16:32 UTC, rhatdan commented
@edsantiago @baude @Luap99 @flouthoc PTAL

2021-09-16 16:33 UTC, edsantiago commented
This seems like it will just make *all* the man pages broken?

2021-09-16 18:45 UTC, rhatdan commented
Why? I think the tests are broken.  Looking at this from a website looks perfect.

2021-09-16 19:23 UTC, Luap99 commented
I am fine with this change but this will not fix the "links in markdown tables" problem. To fix the links https://github.com/containers/podman/pull/11614 is needed.

2021-09-16 19:26 UTC, Luap99 requested changes

2021-09-16 19:26 UTC, Luap99 commented on docs/source/Commands.rst
> +:doc:`container <markdown/podman-containers.1>` Manage Containers
```suggestion
:doc:`container <markdown/podman-container.1>` Manage Containers
```

2021-09-17 08:37 UTC, Luap99 approved these changes
LGTM

2021-09-17 10:35 UTC, giuseppe approved these changes
/lgtm

2021-09-17 10:35 UTC, rhatdan commented
@flouthoc @saschagrunert @giuseppe @containers/podman-maintainers PTAL

2021-09-17 10:35 UTC, merged