libpod: change mountpoint ownership when creating overlays on top of external rootfs
containers/podman pull request #11937
Opened 2021-10-12 11:19 UTC by flouthoc

Allow chainging ownership of mountpoint created on top of external overlay
rootfs to support use-cases when custom --uidmap and --gidmap are
specified.

TLDR
Supports `uidmap` and `gidmap` with overlays on top of external rootfs specified with 
`--rootfs </path>:O`

Example 
```
podman run --uidmap 0:1000:1000 --rm --rootfs /tmp/foo:O bash
```

2021-10-12 11:33 UTC, giuseppe requested changes
I still see an issue when using this patch:

```
# bin/podman run --uidmap 0:1000:1000 --rm --rootfs /tmp/foo:O bash
Error: make `/var/lib/containers/storage/overlay-containers/1df9c17515d7ebb92d6b36fa2790c5c7c501a7509a0acffefc03711c9b96909f/rootfs/merge` private: Permission denied: OCI permission denied
```

2021-10-12 11:33 UTC, giuseppe commented on libpod/container_internal.go
> +		if err := os.Chown(mountPoint, c.RootUID(), c.RootGID()); err != nil {
I think we need to map the `/merge` directory for the overlay mount (and make sure it is accessible with `makeAccessible`) not the mount point.

2021-10-19 10:44 UTC, flouthoc commented on libpod/container_internal.go
> +		if err := chown.ChangeHostPathOwnership(mountPoint, true, int(hostUID), int(hostGID)); err != nil {
yes changed to false we add to man page, that users are responsible to configure ownership of underlying rootfs.

2021-10-19 13:56 UTC, giuseppe approved these changes
LGTM

2021-10-19 17:14 UTC, merged