Display help text on empty subcommand by default
containers/podman pull request #11953
Opened 2021-10-13 09:56 UTC by markusthoemmes

#### What this PR does / why we need it:

This is a small quality-of-life improvement, where instead of guiding the user to use `--help` when they didn't enter a specific subcommand, it shows the help text by default.

https://github.com/kubernetes/kubernetes/blob/efce40b931b5250498b9d8bcd67f987095ab6f74/hack/lib/util.sh#L714 in Kubernetes inspired me to do this. The `docker` CLI is behaving this way as well and Kubernetes uses this to check if `docker buildx` exists. I suppose the K8s side could potentially change in this case as well, but I wanted to see if y'all think this is a worthwhile improvement for human users anyway.

#### How to verify it

Run `podman`. It used to output

```
Error: missing command 'podman COMMAND'
Try 'podman --help' for more information.
```

With this it prints the help text immediately.

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

I realize that this might be contentious in nature and I haven't found an issue relating to this. Please let me know if we should instead open an issue and discuss there first.

2021-10-14 11:07 UTC, rhatdan commented
We should probably do this on subcommands as well, what I don't like is scroll off the screen when you specify a bad option.
```
 $ podman network
Error: missing command 'podman network COMMAND'
Try 'podman network --help' for more information.
$ podman container
Error: missing command 'podman container COMMAND'
Try 'podman container --help' for more information.
```

Git does a nice job at this.

Docker does a better job then us on this also.

Both Git and Docker stack the options at the top and the commands at the bottom, which is probably something we should consider.

2021-10-14 11:28 UTC, rhatdan commented
If it does that would be good.

2021-10-15 15:04 UTC, jwhonce requested changes
Thanks for the PR. Just one change to restore the original semantics.

2021-10-15 15:14 UTC, rhatdan commented on cmd/podman/validate/args.go
> +	return cmd.Help()
Good catch @jwhonce

2021-11-05 10:17 UTC, markusthoemmes commented
@rhatdan @jwhonce thanks for the feedback and sorry for taking a while to  add it. This should be ready for another look now!

2021-11-05 12:38 UTC, rhatdan commented
LGTM
/approve
Thanks @markusthoemmes

2021-11-05 12:38 UTC, rhatdan commented
@jwhonce PTAL

2021-11-06 11:10 UTC, rhatdan commented
@mheon PTAL

2021-11-08 15:29 UTC, markusthoemmes commented
/assign @jwhonce @mheon

2021-11-08 17:22 UTC, mheon commented
/lgtm

2021-11-08 17:23 UTC, merged