test/system: podman exec with short lived commands
containers/podman pull request #12217
Opened 2021-11-08 13:18 UTC by chuanchang

This test case is used for covering rhbz#1972311.

Signed-off-by: Alex Jia <ajia@redhat.com>

#### What this PR does / why we need it:

#### How to verify it

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

2021-11-08 13:25 UTC, vrothberg commented on test/system/075-exec.bats
> +    run_podman exec -til ls /
Could you assign a (random) name to the container instead of `-l`?

2021-11-08 13:36 UTC, Luap99 requested changes
We already have a test for this, however it is disabled because it flakes to much.
https://github.com/containers/podman/blob/d6ef903164512e6fa7903bb0b85a1852117df37b/test/system/450-interactive.bats#L66-L73
Also see this issue https://github.com/containers/podman/issues/10710 for more context

2021-11-08 13:38 UTC, edsantiago commented
What Paul said.

2021-12-09 19:01 UTC, rhatdan commented
It seems that this PR was rejected, because flaky tests.  Closing.  Reopen if I am mistaken.

2021-12-09 19:01 UTC, closed without merging