compat: Add subnet mask behind IP address to match Docker API
containers/podman pull request #12328
Opened 2021-11-17 12:15 UTC by serverwentdown

#### What this PR does / why we need it:

Mismatch between Podman and Docker APIs when listing network containers.

#### How to verify it

On both Docker and Podman, create a container on a network and run:
```
curl -X GET --unix-socket /var/run/docker.sock http://d/networks/<id> | jq
```

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

2021-11-17 18:26 UTC, TomSweeneyRedHat commented
@serverwentdown thanks for the PR.  Our CI requires a test to be added with a PR.  Could you create one or update one?  It would be good to test that the format is as you want it to be.

Changes LGTM otherwise, but I'm not sure if there are dependencies elsewhere for the current format.

2021-11-18 12:46 UTC, Luap99 requested changes
One nit, could you also add a test to https://github.com/containers/podman/tree/main/test/apiv2?

2021-11-18 12:46 UTC, Luap99 commented on pkg/api/handlers/compat/networks.go
> +			ipv6Address := fmt.Sprintf("%s/%d", netData.GlobalIPv6Address, netData.GlobalIPv6PrefixLen)
You have to check that `netData.IPAddress` is not an empty string before comping them to the CIDR. Right now you will return `/0` is there is no IP. It should just be empty.

2021-11-20 07:05 UTC, serverwentdown commented
@Luap99 I have added an APIv2 test but because the API tests run as rootless, it won't populate the IP address field.

2021-11-20 10:59 UTC, Luap99 approved these changes
LGTM

2021-11-20 11:00 UTC, Luap99 commented
Tanks @serverwentdown, unfortunately you have to rebase to the latest main branch in order to pass the CI tests.

2021-11-21 12:25 UTC, Luap99 commented
/lgtm
/hold

2021-11-23 15:39 UTC, rhatdan commented
Forcing merge to save the planet.

2021-11-23 15:39 UTC, merged

2021-11-23 15:39 UTC, rhatdan commented
Thanks @serverwentdown

2021-12-23 02:14 UTC, serverwentdown commented
@rhatdan @Luap99 is there any plans for this bugfix to be released in v3 or is the goal v4?

2021-12-23 09:10 UTC, Luap99 commented
> @rhatdan @Luap99 is there any plans for this bugfix to be released in v3?

@mheon PTAL

2021-12-23 12:44 UTC, rhatdan commented
No plans for that now.

2021-12-23 14:10 UTC, mheon commented
Given when this merged, I probably already attempted to backport it to v3.4.2 or v3.4.3, but the patch had cherry-pick conflicts against that branch so I moved on.

2022-02-20 09:48 UTC, geraldwuhoo commented
Has this feature been added in v4? Been waiting on this for k3d on podman.

2022-02-20 11:35 UTC, Luap99 commented
@geraldwuhoo It should be in v4.0