fix healthcheck timeouts and ut8 coercion
containers/podman pull request #12614
Opened 2021-12-15 20:10 UTC by baude

this commit fixes two bugs and adds regression tests.

when getting healthcheck values from an image, if the image does not
have a timeout defined, this resulted in a 0 value for timeout.  The
default as described in the man pages is 30s.

when inspecting a container with a healthcheck command, a customer
observed that the &, <, and > characters were being converted into a
unicode escape value.  It turns out json marshalling will by default
coerce string values to ut8.

Fixes: bz2028408

Signed-off-by: Brent Baude <bbaude@redhat.com>

#### What this PR does / why we need it:

#### How to verify it

#### Which issue(s) this PR fixes:

#### Special notes for your reviewer:

2021-12-15 20:10 UTC, baude commented
@jwhonce ptal

2021-12-15 20:48 UTC, mheon commented on test/e2e/healthcheck_run_test.go
> +	It("", func() {
Needs a name

2021-12-15 20:49 UTC, mheon commented
Nit on tests, code LGTM

2021-12-15 21:27 UTC, jwhonce requested changes

2021-12-15 21:27 UTC, jwhonce commented on cmd/podman/inspect/inspect.go
> +	"encoding/json"
Why remove comment? Anyone who tries to use json-iterator (like most of cmd/podman) will have to debug the issue again...

2021-12-15 21:27 UTC, jwhonce commented on cmd/podman/inspect/inspect.go
> +		fmt.Println(ctrData[0].Config.Healthcheck.Test)
Is this debugging output?

2021-12-16 01:05 UTC, TomSweeneyRedHat commented
Changes LGTM, but the test system isn't buying it.

2021-12-16 09:52 UTC, vrothberg reviewed
Great catch. As mentioned in the meeting, I wouldn't have guessed that the JSON library would do that.

2021-12-16 09:52 UTC, vrothberg commented on libpod/define/healthchecks.go
> +var (
const?

2021-12-16 19:20 UTC, rhatdan commented
/lgtm
/hold

2021-12-17 22:00 UTC, mheon commented
Needs a rebase

2021-12-21 17:15 UTC, rhatdan commented
/lgtm

2022-01-06 20:13 UTC, rhatdan commented
/lgtm

2022-01-06 22:35 UTC, rhatdan commented
/hold cancel

2022-01-06 22:36 UTC, merged