Fix permission on secrets directory
containers/podman pull request #12813
Opened 2022-01-11 19:06 UTC by rhatdan

This directory needs to be world searchable so users can access it from
different user namespaces.

Fixes: https://github.com/containers/podman/issues/12779

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

2022-01-11 19:20 UTC, rhatdan commented
@ashley-cui @containers/podman-maintainers PTAL

2022-01-11 19:23 UTC, edsantiago requested changes
Minor quibbles, none of them showstoppers, but the missing tmpfile cleanup is enough to make me request a re-push. (The others, up to you).

2022-01-11 19:23 UTC, edsantiago commented on test/system/170-run-userns.bats
> +    run_podman rm --all --force
Why not just `run --rm` in line 93?

2022-01-11 19:23 UTC, edsantiago commented on test/system/170-run-userns.bats
> +    secret_file="/tmp/secret$(random_string 12)"
If you use `secret_file=$PODMAN_TMPDIR/secret$(random_string 12)` you don't have to `rm -f $secret_file` at the end.

2022-01-11 19:23 UTC, edsantiago commented on test/system/170-run-userns.bats
> +    fi
Very minor duplication-avoiding suggestion:
```bash
    ns_user="containers"
    if is_rootless then
        ns_user=$(id -un)
    fi
    egrep -q "$ns_user:" /etc/subuid || skip "no IDs allocated for user '$ns_user'"
```

2022-01-11 20:02 UTC, edsantiago commented on test/system/170-run-userns.bats
> +    egrep -q "ns_user:" /etc/subuid || skip "no IDs allocated for current user"
Missing dollar sign, should be `$ns_user`

2022-01-11 20:03 UTC, edsantiago commented on test/system/170-run-userns.bats
> +    egrep -q "ns_user:" /etc/subuid || skip "no IDs allocated for current user"
Oh, and can you change `current user` to `user '$ns_user'`?

2022-01-11 20:04 UTC, edsantiago commented on test/system/170-run-userns.bats
> +    run_podman run -rm --secret=${test_name} --userns=auto:size=1000 $IMAGE cat /run/secrets/${test_name}
One more: it should be `--rm` (two dashes, not one)

2022-01-11 21:46 UTC, edsantiago approved these changes

2022-01-11 22:01 UTC, ashley-cui reviewed
LGTM

2022-01-12 00:35 UTC, TomSweeneyRedHat commented
Changes LGTM, but the test failure doesn't look to be a flake.

2022-01-12 00:51 UTC, edsantiago commented
Rebase needed to fix buildah-bud tests; see #12818 for details.

2022-01-12 08:03 UTC, flouthoc approved these changes

2022-01-12 08:03 UTC, flouthoc commented
/lgtm
/approve

2022-01-12 08:04 UTC, merged