Pass configmaps from API query to play kube
containers/podman pull request #13015
Opened 2022-01-26 10:00 UTC by machacekondra

This PR fixes the passing of the configmaps via the REST API, previously
the configmaps wasn't able to pass because the query with configmaps
wasn't parsed.

[NO NEW TESTS NEEDED]
[NO TESTS NEEDED]

Signed-off-by: Ondra Machacek <omachace@redhat.com>

When running code such as:
```golang
        manifestPath := "podyaml"
	configMaps := []string{"configmap.yaml"}
	options := play.KubeOptions{
		ConfigMaps: &configMaps,
	}
	report, err := play.Kube(connText, manifestPath, &options)
	if err != nil {
	  fmt.Printf("Error: %v", err)
	}
	fmt.Printf("Report: %v", report)

```

previously the configmaps wasn't passed, with this code it is.

2022-01-26 12:32 UTC, rhatdan commented
/approve
LGTM
@umohnani8 @jwhonce PTAL

2022-01-26 17:19 UTC, umohnani8 commented
LGTM
Will wait on a final review from @jwhonce

2022-01-26 17:51 UTC, Luap99 requested changes
Please see https://github.com/containers/podman/pull/12371
The configmap should be added to the payload. Sending a path via API does not work when your client is on another system. I do not think we should add this to the API

2022-01-27 10:15 UTC, machacekondra commented
> Please see #12371 The configmap should be added to the payload. Sending a path via API does not work when your client is on another system. I do not think we should add this to the API

Ah right, I think that this should be then removed from bindings? So it users are not confused. I am closing this PR.

2022-01-27 10:15 UTC, closed without merging

2022-01-27 13:26 UTC, rhatdan commented
Interested in opening a PR to remove from the bindings.
Should we even support remote podman play kube, until we fully suppor it remotely.
For example I am not sure --build works.