benchmarking Podman: proof of concept
containers/podman pull request #13835
Opened 2022-04-12 09:52 UTC by vrothberg

Add a proof of concept for benchmarking Podman.  The benchmarks are
implemented by means of the end-to-end test suite but hidden behind
a `benchmarks` build tag.  Running `make localbenchmarks` will run
`test/e2e` with the specific build tag and set ginkgo's "focus" to
the specific "Podman Benchmark Suite" to only run this spec and skip
all others.

ginkgo will print a report before terminating listing the CPU and memory
stats for each benchmark.  New benchmarks can easily be added via the
`newBenchmark` function that also supports adding an `init()` function
to each benchmark which allows for performing certain setups for the
specific benchmark.  For instance, benchmarking `podman start` requires
creating a container beforehand.

Podman may be called more than once in the main function of a benchmark
but note that the displayed memory consumption is then a sum of all
Podman invocations.  The memory consumption is collected via
`/usr/bin/time`.

A benchmark's report is split into CPU and memory as displayed below:

```
[CPU] podman images:
  Fastest Time: 0.146s
  Slowest Time: 0.187s
  Average Time: 0.180s ± 0.015s
[MEM] podman images:
  Smallest: 41892.0KB
   Largest: 42792.0KB
   Average: 42380.7KB ± 286.4KB
```

Note that the benchmarks are not wired into the CI yet.  They are meant
as a proof of concept.  More benchmarks and the plumbing into CI will
happen in a later change.

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

2022-04-12 10:43 UTC, rhatdan commented
LGTM

2022-04-12 11:24 UTC, vrothberg commented
@baude PTAL

I consider the spike done. Once merged, I want to sit down with you and check which commands (and variations) we want to benchmark.

2022-04-12 16:03 UTC, vrothberg commented on test/utils/utils.go
> +	RunBenchmarks        = false
This can be removed.

2022-04-12 16:03 UTC, vrothberg commented on test/e2e/benchmarks_test.go
> +	// Function is run before `function`.
```suggestion
	// Function is run before `main`.
```

2022-04-14 07:33 UTC, vrothberg commented
@baude PTAL

2022-04-19 15:32 UTC, TomSweeneyRedHat commented
LGTM
@edsantiago PTAL

2022-04-19 16:55 UTC, edsantiago reviewed
Fails for me on my laptop:
```
Failed to compile e2e:

# github.com/containers/podman/v4/test/e2e [github.com/containers/podman/v4/test/e2e.test]
test/e2e/benchmarks_test.go:60:3: undefined: tempdir
test/e2e/benchmarks_test.go:64:33: undefined: tempdir
```
Not sure if this is a problem on my end, I will investigate but wanted to get this sent out early

2022-04-19 16:55 UTC, edsantiago commented on Makefile
> +		      test/e2e/. HACK=hack/.
`HACK=hack/.` seems like a NOP here, very likely a copy-paste error. Possibly harmless, but misdirecting and time-wasting.

2022-04-19 17:00 UTC, edsantiago commented on test/e2e/benchmarks_test.go
> +		tempdir, err = CreateTempDirInTempDir()
Looks like the error is here, `=` should be `:=` and the `err` in line 55 needs to go.

But then, if I fix that, I somehow end up with a tmpdir called `/tmp/root` which is terrifying. Now I'm trying to figure out the source of that bug, but if it's easier for you to track down, I'd appreciate getting that fixed.

2022-04-19 17:43 UTC, edsantiago requested changes
Yeah, there's definitely something super-broken here wrt tempdir. Please fix in such a way that there is no use of `/tmp/root` or `/tmp/runroot` or anything like that; I'll take a fresh look once that's resolved.

2022-04-20 09:35 UTC, vrothberg commented
> Yeah, there's definitely something super-broken here wrt tempdir. Please fix in such a way that there is no use of `/tmp/root` or `/tmp/runroot` or anything like that; I'll take a fresh look once that's resolved.

Great catch! Note that it predates this PR; it's using what other e2e tests are doing already.  I prefer to defer that to another PR.

2022-04-20 12:22 UTC, edsantiago approved these changes

2022-04-20 12:23 UTC, edsantiago commented
>Note that it predates this PR;

Indeed it does - how can I not have caught this before...? Thanks for checking, and for fixing the other problems I noted. LGTM.

2022-04-20 12:39 UTC, rhatdan commented
/lgtm

2022-04-20 12:41 UTC, merged