Deleting an n use image should return conflict not system error
containers/podman pull request #14228
Opened 2022-05-12 21:07 UTC by rhatdan

Fixes: https://github.com/containers/podman/issues/14208

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note

```

2022-05-13 09:38 UTC, vrothberg reviewed
Code LGTM
Test needs a massage

2022-05-13 09:38 UTC, vrothberg commented on test/apiv2/10-images.at
> +podman create test1 echo hi
```suggestion
podman create --name=test1 test1 echo hi
```

2022-05-13 17:11 UTC, jwhonce requested changes
Test not covering new code.

2022-05-13 17:11 UTC, jwhonce commented on test/apiv2/10-images.at
> +t DELETE libpod/images/test1:latest 409
The change is in the compat handler while the test is calling the libpod handler.
```suggestion
t DELETE images/test1:latest 409
```

2022-05-13 17:11 UTC, jwhonce commented on test/apiv2/10-images.at
> +t DELETE libpod/images/test1:latest 200
```suggestion
t DELETE images/test1:latest 200
```

2022-05-18 10:20 UTC, vrothberg reviewed
LGTM
@jwhonce PTanotherL

2022-05-18 14:56 UTC, jwhonce commented
/lgtm

2022-05-18 15:48 UTC, merged