Fix podman pod unpaue TODO
containers/podman pull request #14370
Opened 2022-05-25 19:37 UTC by umohnani8

Update the podman pod unpause to only show the paused
containers with autocomplete.
Fix a typo in the help command.
Update the unpause function to only attempt an unpause
on pasued pods instead of all the pods.
Update the tests accordingly.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman pod unpause only shows paused pods when using autocomplete

```

2022-05-26 15:04 UTC, mheon commented
LGTM

2022-05-26 17:45 UTC, rhatdan commented
LGTM
But tests are not happy.

2022-05-26 18:30 UTC, TomSweeneyRedHat commented
LGTM

2022-05-26 18:30 UTC, TomSweeneyRedHat commented
/lgtm
/hold # for happy tests

2022-05-30 15:03 UTC, Luap99 requested changes
It looks like this change is breaking the behaviour.
As per `createPodStatusResults()` a pod is only considered paused when all containers are paused.
Previously a pod unpause would try to unpause all containers. Now this no longer works and thus can break users. I think we should keep this behaviour.

2022-07-05 11:56 UTC, vrothberg commented
@umohnani8 can you rebase before merging?

2022-07-05 11:56 UTC, vrothberg commented
@Luap99 PTanotherL

2022-07-05 14:33 UTC, umohnani8 commented
Rebased

2022-07-05 14:42 UTC, Luap99 approved these changes
LGTM

2022-07-05 17:33 UTC, merged