Add support for special IP designator `host-gateway` in `--add-hosts`.
containers/podman pull request #14392
Opened 2022-05-26 23:22 UTC by willmtemple

Implements the behavior described in https://github.com/containers/podman/issues/14390 (feature request).

`host-gateway` is a special designator used in the IP address position of `--add-host` entries. It maps to the container's `host.containers.internal` IP address. moby-engine/docker CLI implement this same option.

This implementation:

- Allows the string "\<hostname\>:host-gateway" as a valid host entry (it is carried through all options that derive from the `NetOptions.AddHosts` field).
- Replaces host entries that are mapped to "host-gateway" with the container's `host.containers.internal` IP address during `etchosts` construction in the linux libpod container driver.

Signed-off-by: Will Temple <will@wtemple.net>

Closes #14390 

#### Example:

```
$ bin/podman run -it --rm --add-host testhostname:host-gateway alpine   
/ # cat /etc/hosts
192.168.1.228   testhostname
127.0.0.1       localhost
::1     localhost
192.168.1.228   host.containers.internal
10.0.2.100      1b6fcb8904fe vibrant_wescoff
/ # ping testhostname
PING testhostname (192.168.1.228): 56 data bytes
64 bytes from 192.168.1.228: seq=0 ttl=42 time=0.135 ms
```

#### Does this PR introduce a user-facing change?

Is this what your CI is expecting?

```release-note
Adds support for the special string `host-gateway` as an "IP address" when using the `--add-host` command-line flag. A mapping to "host-gateway" results in the given hostname being mapped to the host IP address (the same IP as for the default `host.containers.internal` address) in the `/etc/hosts` file within the container.
```

2022-05-27 15:19 UTC, TomSweeneyRedHat commented on cmd/podman/parse/net.go
> +	}
Could you update the function comment please to cover this new case?

2022-05-28 11:10 UTC, rhatdan commented
@Luap99 PTAL

2022-05-29 08:54 UTC, Luap99 requested changes
This has to be fixed in the etchosts package instead of this workaround in libpod. Otherwise it will not work for podman build.

2022-06-01 20:07 UTC, willmtemple commented
@Luap99 Do you think it's sufficient to just allow passing `host-gateway` as an IP string to libnetwork/etchosts? We could just do the conversion to the host's interface IP there instead of here if it's okay for the `host-gateway` string to flow through the rest of the pod creation pipeline.

2022-06-02 11:52 UTC, Luap99 commented
> @Luap99 Do you think it's sufficient to just allow passing host-gateway as an IP string to libnetwork/etchosts? We could just do the conversion to the host's interface IP there instead of here if it's okay for the host-gateway string to flow through the rest of the pod creation pipeline.

Yes that is what I had in mind.

2022-06-21 20:08 UTC, rhatdan commented
@willmtemple @Luap99 what is going on with this PR?

2022-07-25 20:35 UTC, rhatdan commented
@Luap99 Update?

2023-01-17 10:04 UTC, vrothberg commented
The PR looks abandoned.  Please re-open when you find time to get back to it.

2023-01-17 10:04 UTC, closed without merging