Fix runtime check during restore
containers/podman pull request #14717
Opened 2022-06-23 20:09 UTC by ZeyadYasser

[cfg.RuntimePath](https://github.com/containers/podman/blob/8e88abda85f7bf44b6857ad5d62c8ef58206fce5/cmd/podman/root.go#L146) was set to default runtime, so the empty string check fails. Instead we could check if the flag was changed.

Fixes: #11945

Signed-off-by: Zeyad Yasser <zeyady98@gmail.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-06-24 15:28 UTC, ZeyadYasser commented
[Runtime verification test for container checkpoint with export](https://github.com/containers/podman/blob/4274906a80c830492e0634602350c1626288e968/test/e2e/checkpoint_test.go#L1492)
used the default runtime for test which causes test to always
pass. Problem rises when using non-default runtime, then doing
a restore.
I just forced using a non-default runtime during container creation to trigger the edge case I faced.

2022-06-24 16:19 UTC, mheon commented
@edsantiago PTAL

2022-06-24 19:08 UTC, ZeyadYasser commented
https://api.cirrus-ci.com/v1/artifact/task/4817234857033728/ginkgo_node_logs/test/e2e/ginkgo-node-3.log

Looks like `--runtime` is implicitly set to the default runtime, I will look into a way to remove the `--runtime` arg.

2022-06-25 19:01 UTC, ZeyadYasser commented
> https://api.cirrus-ci.com/v1/artifact/task/4817234857033728/ginkgo_node_logs/test/e2e/ginkgo-node-3.log
> 
> Looks like `--runtime` is implicitly set to the default runtime, I will look into a way to remove the `--runtime` arg.

UPDATE: I created a new test to address this problem.

2022-06-27 14:04 UTC, edsantiago requested changes
Test LGTM overall, but needs some work. Thanks @ZeyadYasser 

(and OBTW I suspect the team will ask you to squash your commits)

2022-06-27 14:04 UTC, edsantiago commented on test/e2e/checkpoint_test.go
> +		fileName := "/tmp/checkpoint-" + cid + ".tar.gz"
I know this is copy-paste from elsewhere, but you might take the opportunity to make this variable name more descriptive

2022-06-27 14:04 UTC, edsantiago commented on test/e2e/checkpoint_test.go
> +		if !strings.Contains(defaultRuntime, "crun") {
Okay, why `Contains`? You're asking for `.Name`. It should be safe to use `Equals` here.

2022-06-27 14:04 UTC, edsantiago commented on test/e2e/checkpoint_test.go
> +			Skip("Test requires crun to be the default runtime")
Hint: a future maintainer seeing this message would reeeeeeeeally appreciate something like "Default runtime is %q; this test requires crun to be default".

2022-06-28 13:40 UTC, edsantiago approved these changes

2022-06-28 13:53 UTC, rhatdan commented
LGTM but reverse your PRs.

2022-06-28 16:54 UTC, edsantiago commented
@mheon here we go again with [the timeout](https://api.cirrus-ci.com/v1/task/6116050067521536/logs/main.log). I've restarted anyway.

2022-06-28 17:20 UTC, mheon commented
@vrothberg Looks like we're seeing timeouts in `podman wait`, specifically in remote Podman, after the Gitlab patches landed.

2022-06-28 17:21 UTC, mheon commented
At least seem to be significantly rarer than the other issues. I don't see any obvious cause, unfortunately.

2022-06-28 19:07 UTC, merged