[WIP] Cirrus: Add "su" system-test matrix
containers/podman pull request #14992
Opened 2022-07-20 15:57 UTC by cevich

#### Does this PR introduce a user-facing change?

```release-note
Include "su" system testing in upstream CI
```

2022-07-20 16:20 UTC, edsantiago requested changes

2022-07-20 16:41 UTC, edsantiago commented
Can you remind me why we need this? There's nothing in the commit message or PR. I vaguely remember you commenting on it in scrum last week, and saying that it's something I asked for, but I really don't think this is worth the complexity. We test `su` in gating tests, and yeah, that catches occasional `XDG` problems, but probably not enough to add so much more hassle to our CI.

2022-07-20 19:34 UTC, cevich commented on contrib/cirrus/runner.sh
> +        exec su $ROOTLESS_USER $GOSRC/$SCRIPT_BASE/runner.sh
With `-c` and `-` there's probably no point in running this test vs the `ssh` variant.

2022-07-20 19:34 UTC, cevich commented on contrib/cirrus/runner.sh
> +        msg "Re-executing runner through ssh as user '$ROOTLESS_USER'"
Good suggestion.

2022-07-20 19:34 UTC, cevich commented
Ugh:

`+ exec su some12599dude /var/tmp/go/src/github.com/containers/podman/./contrib/cirrus/runner.sh
/usr/share/automation/lib/console_output.sh: line 70: /dev/stderr: Permission denied`

That's what I was afraid might happen.

2022-07-20 19:39 UTC, cevich commented
> Can you remind me why we need this? There's nothing in the commit message or PR.

Because the team asked for it.  Apparently `su podman foo` is something that's suppose to work and therefore should be tested.  Perhaps it's something that works in docker?  In any case, with podman and buildah, the tty & pty ownership problem is a long-standing problem (i.e. using su or sudo inside a Dockerfile also breaks in this way).

> We test su in gating tests, and yeah, that catches occasional XDG problems, but probably not enough to add so much more hassle to our CI.

That was part of the other reason IIRC, the team wanted to catch these problems earlier in the development cycle.

Anywho...I agree, the extra complexity and gymnastics is probably not worth it in upstream CI.  I'll bring this up in SCRUM.

2022-07-20 19:45 UTC, edsantiago commented
I'm super confused. Do you mean `sudo`? `su user foo` does not work, has never worked in all the years I've been around. You either do `sudo user foo`, or `su user -c "foo"`.

Anyhow, apart from that, yeah, let's figure out what problem we're trying to solve. It might be pretty easy to just add a test that runs `su/sudo` and tests a handful of likely-to-fail podman commands.

2022-07-20 19:53 UTC, cevich commented
> su user foo does not work

Woops, yeah, I meant sudo.  In any case, `-l` or `-` is still going to result in `/dev/stderr: permission denied` all over the place.

> It might be pretty easy to just add a test that runs su/sudo and tests a handful of likely-to-fail podman commands.

Meh, I'd say probably even that isn't worth the extra complexity needed to support it.

2022-07-21 09:20 UTC, Luap99 commented
see https://github.com/containers/podman/issues/14603

su or sudo are not supposed to work since they do not create a proper login session and without the login option even have the wrong XDG vars set.

As @edsantiago pointed out (https://github.com/containers/podman/pull/14992#discussion_r925812030) you need to enable lingering and the use `su -l ...` or `su - ...` to make it work.

2022-07-21 14:02 UTC, cevich commented
> you need to enable lingering and the use su -l ... or su - ... to make it work.

Thanks Paul.  Yeah, and that totally beggs the issue, since at that point we're not very different from the `rootless` (ssh-based) environment.  I'm with Ed, I think we should abandon this effort.  A singular test for the #14603 fix should be more than sufficient.

2022-07-22 16:42 UTC, rhatdan commented
I am fine with that.  Although I would want to hear @vrothberg @baude @mheon @giuseppe opinion.

2022-07-22 16:45 UTC, mheon commented
My understanding is that we began this because the RHEL gating tests use `su` and we wanted to try and catch problems in them in CI. However, Paul is entirely correct that we do not expect sudo/su to work as a general principle. Given that, I'm OK with aborting this effort; dealing with problems as they arise in RHEL CI is inconvenient, but testing something that should never be used in production on every pull request seems worse.

2022-07-22 21:10 UTC, giuseppe commented
I agree with Matt.  Let's not test stuff that is not even supposed to work.

2022-07-25 14:45 UTC, cevich commented
SGTM, thanks everyone for considering this.

2022-07-25 14:45 UTC, closed without merging