Add support for podman context as alias to podman system connection
containers/podman pull request #15072
Opened 2022-07-26 13:16 UTC by rhatdan

Alias
podman context use -> podman system connection default
podman context rm -> podman system connection rm
podman context create -> podman system connection add
podman context ls ->podman system connection ls

Podman context is a hidden command, but can be used for existing scripts
that assume Docker under the covers.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
podman context command is a hidden command available for Docker compatibility.

```

2022-07-26 13:22 UTC, Luap99 requested changes
I don't think it makes sense to just alias the names. If we need docker compat we have to actually match the docker output and input (cli arguments).

2022-07-26 13:51 UTC, vrothberg commented
> I don't think it makes sense to just alias the names. If we need docker compat we have to actually match the docker output and input (cli arguments).

Agreed.  Let's discuss which goal we try to reach.  If it's docker compat, we probably need to tackle it command-by-command/commit-by-commit to make it reviewable.

2022-07-26 14:53 UTC, rhatdan commented
Yup, I agree, although don't have time or understanding of how these match up.  I was hoping to get this to pass tests and ask people who are hitting issues, to see if this gets them further.  Then if someone (intern?) wants to take it over and drive it home for missing CLI and Output.

I have a feeling getting use and list to work would get us 95% of the way towards making more tools work.

2022-09-15 19:26 UTC, rhatdan commented on test/system/272-system-connection.bats
> -    run_podman system connection add --default $c2 tcp://localhost:54321
I don't think it is worth it, but I would rather get this merged and then open a PR to add more tests.

2022-09-15 19:27 UTC, edsantiago commented on test/system/272-system-connection.bats
> -    run_podman system connection add --default $c2 tcp://localhost:54321
That's fine with me.

2022-09-19 10:56 UTC, rhatdan commented
@cdoern @vrothberg @giuseppe @flouthoc PTAL
@containers/podman-maintainers PTAL

2022-09-19 15:31 UTC, giuseppe approved these changes
/lgtm

2022-09-19 15:35 UTC, merged