Add interface for apple hypervisor
containers/podman pull request #15199
Opened 2022-08-04 18:33 UTC by baude

The new apple silicon processesors (m1/m2) are capable of using a performent apple
hypervisor (included in macos).  Our "virtual providers" for podman
machine are part of an interface design.  This PR provides an
implementation of the interface to begin the work for supporting the
apple hypervisor.  It is basically only a skeletal PR.

The actual code for using the hypervisor and launching a machine will
come as several new PRs following the inclusion of this one.

There will likely be code reuse between the applehv and qemu code; but
none of that code is being moved at this time.  It will be moved "on
demand" during development.

[NO NEW TESTS NEEDED]

Signed-off-by: Brent Baude <bbaude@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note

```

2022-08-05 06:59 UTC, vrothberg reviewed
LGTM
Restarted the flaked bud test.

@containers/podman-maintainers PTAL

2022-08-05 07:04 UTC, Luap99 requested changes

2022-08-05 07:04 UTC, Luap99 commented on pkg/machine/apple/machine.go
> +package applehv
The dir is called apple but the package applehv, please make it consitent

2022-08-05 07:04 UTC, Luap99 commented on pkg/machine/apple/machine.go
> +// +build arm64,!windows,!linux
This must use the darwin build tag, not linux and windows would also include BSDs for example

2022-08-05 18:15 UTC, TomSweeneyRedHat commented
Other than @Luap99 's comments, LGTM

2022-08-09 18:24 UTC, baude commented
merge me

2022-08-09 19:28 UTC, rhatdan commented
/lgtm

2022-08-09 19:31 UTC, merged