[CI:DOCS] Cirrus: Fix win installer task
containers/podman pull request #16169
Opened 2022-10-13 21:01 UTC by cevich

ref: https://github.com/containers/podman/pull/16167

According to Cirrus-support, defining and using `$CIRRUS_DEFAULT_WORK`
is responsible for causing a strange race condition on windows.  This is
impacting the agent's ability to clone with errors like:

```
Using built-in Git...
Cloning refs/heads/main...
Failed to clone: read ${CIRRUS_DEFAULT_WORK}\.git\HEAD: The process
cannot access the file because another process has locked a portion of
the file.!
```

Fix this by hard-coding a work directory for this windows task.

#### Does this PR introduce a user-facing change?

```release-note
None
```

2022-10-13 21:02 UTC, cevich commented
@n1hility PTAL when you get a chance.  I *think* this is the right thing to do, but am certainly uncertain :grin:

2022-10-13 21:32 UTC, n1hility commented
@cevich im not sure if this should be in a local tmp, let me check what the default normally is

2022-10-13 22:04 UTC, n1hility requested changes
A root location is probably fine, but I posted a suggestion above to put it under the users temp dir which matches what they do by default.

2022-10-14 12:16 UTC, cevich commented
Thanks Jason.

This should be ready to merge assuming CI is happy.

2022-10-14 12:24 UTC, cevich commented
@containers/podman-maintainers PTAL - this is affecting all of CI.

2022-10-14 13:13 UTC, baude commented
LGTM

2022-10-14 21:46 UTC, rhatdan commented
/lgtm
/approve

2022-10-14 21:50 UTC, merged