system df: fix image-size calculations
containers/podman pull request #16211
Opened 2022-10-18 11:24 UTC by vrothberg

Fix two bugs in `system df`:

1.  The total size was calculated incorrectly as it was creating the sum of all image sizes but did not consider that a) the same image may be listed more than once (i.e., for each repo-tag pair), and that b) images share layers.

    The total size is now calculated directly in `libimage` by taking multi-layer use into account.

2.  The reclaimable size was calculated incorrectly.  This number indicates which data we can actually remove which means the total size minus what containers use (i.e., the "unique" size of the image in use by containers).

Fixes: #16135
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug where `podman system df` reported wrong image sizes.
```

2022-10-18 12:02 UTC, vrothberg commented
The failures seem to be triggered by containers/storage@main

2022-10-18 12:04 UTC, edsantiago requested changes
Could you run your new tests against `main`? They pass for me, which means you're not actually testing your changes.

2022-10-18 12:04 UTC, edsantiago commented on test/system/320-system-df.bats
> +    run_podman system df --format '{{ .Reclaimable }}'
nitty nit: inconsistent use of whitespace in formats, is that deliberate?

2022-10-18 14:51 UTC, vrothberg commented on test/system/320-system-df.bats
> +    run_podman system df
Yes :) thanks!

2022-10-18 14:52 UTC, vrothberg commented
> The failures seem to be triggered by containers/storage@main

For now I forced back the previous c/storage version via a `replace`.  @mtrmac @rhatdan PTAL

2022-10-18 14:52 UTC, vrothberg commented
Easy reproducer among others:
```
$ go get github.com/containers/storage@main
$ make vendor && make podman
$ ./test/apiv2/test-apiv2 images
```

2022-10-18 14:59 UTC, mheon commented
Code LGTM

2022-10-18 15:03 UTC, edsantiago requested changes
Tests are still broken, in the sense that they pass on `main`. You are not testing anything new. Can you please find a way to write tests that break on `main` and pass with this PR?

2022-10-18 15:33 UTC, vrothberg commented
> Tests are still broken, in the sense that they pass on `main`. You are not testing anything new. Can you please find a way to write tests that break on `main` and pass with this PR?

Thanks for checking, Ed! Will do :+1: 

Also need to update the apiv2 tests:
```
[+0165s] not ok 993 [45-system] GET libpod/system/df : output
[+0165s] #  expected: {"Images":[],"Containers":[],"Volumes":[]}
[+0165s] #    actual: {"ImagesSize":0,"Images":[],"Containers":[],"Volumes":[]}
```

2022-10-19 11:40 UTC, vrothberg commented
@edsantiago can you take another look at the tests?

2022-10-19 14:42 UTC, edsantiago commented
ARGH! Sorry; left tests running this morning, moved on to something else. New test looks great, and fails (as it should) on main.  Thank you!
/lgtm

2022-10-19 14:46 UTC, merged