fix `podman system connection - tcp` flake
containers/podman pull request #16929
Opened 2022-12-23 09:46 UTC by vrothberg

The test was only waiting for the port to be ready but that doesn't imply the server being ready to serve requests.  Hence, add a loop waiting for the `info` call to succeed.

Fixes: #16916
Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>

#### Does this PR introduce a user-facing change?

```release-note
None
```

@containers/podman-maintainers PTAL

2022-12-23 10:14 UTC, rhatdan commented
LGTM

2022-12-23 14:03 UTC, vrothberg commented
> Failed tests (1):
 - 337 podman system connection - tcp
 
 :rofl:

2022-12-23 14:16 UTC, rhatdan commented
I guess if this fails over 10 seconds, we might be looking at a different problem.

2023-01-02 07:52 UTC, vrothberg commented
> I guess if this fails over 10 seconds, we might be looking at a different problem.

I copy-pasted the loop but should have altered the break-condition. Will update.

2023-01-02 10:05 UTC, vrothberg commented
@containers/podman-maintainers PTAL

2023-01-02 17:37 UTC, edsantiago requested changes
LGTM with one change request.

For extra credit: if you copypasted this loop from elsewhere, and that elsewhere also has an unquoted question mark, could you also fix that one? I see two instances in 255-auto-update, but those can't possibly be the ones you copied, so I'll take care of fixing those. TIA.

2023-01-02 21:07 UTC, edsantiago approved these changes

2023-01-02 21:08 UTC, edsantiago commented
/lgtm

Changed my mind. I'll fix the questionmark in #16972 instead, so we can get this merged

2023-01-02 21:12 UTC, merged