Set StoppedByUser earlier in the process of stopping
containers/podman pull request #17077
Opened 2023-01-11 15:31 UTC by mheon

The StoppedByUser variable indicates that the container was requested to stop by a user. It's used to prevent restart policy from firing (so that a restart=always container won't restart if the user does a `podman stop`. The problem is we were setting it *very* late in the stop() function. Originally, this was fine, but after the changes to add the new Stopping state, the logic that triggered restart policy was firing before StoppedByUser was even set - so the container would still restart.

Setting it earlier shouldn't hurt anything and guarantees that checks will see that the container was stopped manually.

Fixes #17069

#### Does this PR introduce a user-facing change?

```release-note
Fixed a bug where containers with a restart policy set could still restart even after a manual `podman stop`.
```

2023-01-11 15:31 UTC, mheon commented
Still needs a test

2023-01-11 16:53 UTC, mheon commented
Test added

2023-01-11 17:19 UTC, edsantiago commented
Do you have a sense for how easy/hard it is to trigger the restart? I started a loop-test, running against `main`, and have not seen it reproduce yet. (Test started a few minutes after you added your test). Any hints on how to manifest the restart bug?

2023-01-11 17:25 UTC, mheon commented
Hm. It should be 100%. I'll look into it more...

2023-01-11 17:40 UTC, edsantiago commented
Here's what I'm seeing: 
* if I run `top` with `restart=always`, then `stop` it, it stays stopped. Even on main.
* if I run `date`, or something else that exits by itself, and then `stop` that, it continues restarting despite my stop.

Does that make any sense to you? Does it help?

2023-01-11 17:50 UTC, edsantiago commented
Update: even with your PR, `podman stop` on the `date` container does not actually keep it stopped:
```console
$ bin/podman run -d --restart=always --name foo quay.io/libpod/testimage:20221018 date
[cid]
$ bin/podman logs foo | wc -l
26
$ bin/podman stop foo
foo
$ bin/podman logs foo|wc -l
195
$ !!
216
```

2023-01-11 17:51 UTC, mheon commented
I think that's probably a bug... Just a separate one. I'll look into what Docker does to be sure.

2023-01-11 18:32 UTC, mheon commented
Yep, that's a separate bug. I'll handle it here.

2023-01-11 18:52 UTC, edsantiago commented
And, #17083 (purported fix for the hang) is merged, please rebase before pushing

2023-01-11 18:56 UTC, mheon commented
@edsantiago The only reproducer I'm aware of uses podman-compose, which introduces enough questions into what's going on that I haven't been able to reproduce without it.

2023-01-11 22:51 UTC, rhatdan commented
LGTM

2023-01-11 23:28 UTC, TomSweeneyRedHat commented on test/e2e/run_test.go
> +		time.Sleep(10 * time.Second)
Does it need the 10?  Could we get away with less?  Perhaps 5?

2023-01-11 23:35 UTC, TomSweeneyRedHat commented
Fedora root tests are timing out after 90 minutes.  @edsantiago or @cevich I'm seeing this in a number of places, do we know the cause?

2023-01-11 23:35 UTC, TomSweeneyRedHat commented
Changes LGTM with happy tests

2023-01-12 01:06 UTC, edsantiago commented
@TomSweeneyRedHat timeout is fixed (:crossed_fingers:)  in #17083

2023-01-12 01:25 UTC, edsantiago requested changes
Blocking for merge because test needed (as discussed in conversation, test passes on `main`). It's possible that there's no reproducer that will fail on main, and maybe that's fine, but I don't want anyone to restart the flakes, have them pass, and then merge this overnight.

2023-01-12 19:45 UTC, mheon commented
At this point, I don't really know what's going on with restart policy and podman-compose, but this does not reproduce on main. Still, we aren't actually *testing* that restart policy works in this way anywhere, so I think this is still worth merging just to make sure we don't regress in the future. I'll rebase to fix CI.

2023-01-12 19:49 UTC, edsantiago commented
SGTM. I was tempted to suggest ditching the expensive test, ... but I guess it's still a good regression check.

2023-01-12 22:54 UTC, edsantiago approved these changes

2023-01-12 23:34 UTC, rhatdan commented
/lgtm

2023-01-12 23:37 UTC, merged