api: fix parsing filters
containers/podman pull request #18345
Opened 2023-04-25 13:26 UTC by vrothberg

The parsing function in `c/common/pkg/filters` is wrong as it concatenates all values to a single key breaking the filters when more than one value is specified.  Hence use the almost duplicate yet correct parsing function in the util package.

I will remove the other function in c/common as it doesn't need to live there.

Fixes: #18092

#### Does this PR introduce a user-facing change?

```release-note
Fix parsing multi-value filters in the REST API.
```

2023-04-25 13:30 UTC, Luap99 commented on pkg/api/handlers/compat/images.go
> +	}
debug leftover?

2023-04-25 13:31 UTC, vrothberg commented on pkg/api/handlers/compat/images.go
> +	}
Very much :^) Thanks for catching

2023-04-25 13:36 UTC, Luap99 approved these changes
LGTM

2023-05-02 09:29 UTC, vrothberg commented
Turns out Docker and Podman clients split the keys/values slightly different.  FWIF, I think the Podman filters are broken as there is now way to know whether, for instance, we want to filter one label as `label=foo` (without a value) or two labels.

But I am not opening this box now.

2023-05-02 09:34 UTC, Luap99 requested changes

2023-05-02 09:34 UTC, Luap99 commented on pkg/domain/infra/abi/images_list.go
> +	}
debug

2023-05-02 09:34 UTC, Luap99 commented on pkg/util/filters.go
> +	logrus.Errorf("Raw: %q", string(raw))
debug

2023-05-02 09:35 UTC, Luap99 commented
> Turns out Docker and Podman clients split the keys/values slightly different. FWIW, I think the Podman filters are broken as there is now way to know whether, for instance, we want to filter one label as `label=foo` (without a value) or two labels.
> 
> But I am not opening this box now.

I am fine with no fixing it in this PR but can you create an issue? This sounds like big deal to me.

2023-05-02 09:41 UTC, vrothberg commented
> I am fine with no fixing it in this PR but can you create an issue? This sounds like big deal to me.

Definitely.  Wanted to do this in any case it made me feel quite uncomfortable, see https://github.com/containers/podman/issues/18412.

2023-05-02 09:47 UTC, Luap99 approved these changes
LGTM

2023-05-02 12:36 UTC, vrothberg commented
@rhatdan PTAL

2023-05-02 15:55 UTC, vrothberg commented
@containers/podman-maintainers PTAL

2023-05-02 21:05 UTC, rhatdan commented
/lgtm

2023-05-02 21:09 UTC, merged

2023-05-03 06:57 UTC, vrothberg commented
/cherry-pick v4.5