[WIP] Podman info output more netavark information
containers/podman pull request #18383
Opened 2023-04-28 07:56 UTC by sstosh

podman info prints the netavark package, path and version.

#### Does this PR introduce a user-facing change?

```release-note
Now podman info prints the netavark package, path and version.
```

2023-04-28 08:44 UTC, Luap99 requested changes
Thanks for doing this, I really like the idea. However I think it would be much better to move the logic directly into the networkBackend in c/common and then add a function there called Info() to return the info you want. Alo I would rather have a proper struct with the info then a generic map.

You can move `packageVersion` and `programVersion` to some c/common util package if needed.

2023-04-28 08:44 UTC, Luap99 commented on libpod/define/info.go
> +	NetworkBackend    map[string]interface{} `json:"networkBackend"`
This is a breaking change and thus cannot be made, I suggest adding a new NetworkBackendInfo field.

2023-05-08 14:13 UTC, baude commented
@sstosh what say you?

2023-05-09 00:12 UTC, sstosh commented
> Just adding a note but totally upto @sstosh , once we have proper implementation in `c/common` as discussed above, I think PR could be easily extended to also include `aardvark-dns` details. Then this will close: #18443

@flouthoc  OK. I also will try to add the feature to show the details of aardvark-dns.

2023-05-09 10:05 UTC, sstosh commented
The output is as shown below:

```yaml
  networkBackend: netavark
  networkBackendInfo:
    aardvark-package: aardvark-dns-1.6.0-1.fc37.x86_64
    aardvark-path: /usr/libexec/podman/aardvark-dns
    aardvark-version: aardvark-dns 1.6.0
    netavark-package: netavark-1.6.0-2.fc37.x86_64
    netavark-path: /usr/libexec/podman/netavark
    netavark-version: netavark 1.6.0
```

```yaml
  networkBackend: cni
  networkBackendInfo: null
```

2023-05-10 05:16 UTC, flouthoc commented
@sstosh Thank you :smile: output LGTM

2023-06-13 04:11 UTC, sstosh commented
The review is ready.

2023-06-13 04:33 UTC, flouthoc approved these changes
LGTM Thanks @sstosh

2023-06-13 08:28 UTC, Luap99 approved these changes
LGTM, thank you

2023-06-13 08:28 UTC, Luap99 commented
/lgtm

2023-06-13 08:33 UTC, merged