Inspecting Containers without health checks return health nil
containers/podman pull request #18807
Opened 2023-06-06 16:35 UTC by rhatdan

Fixed: https://github.com/containers/podman/issues/18792

This will match Docker behaviour.
`

#### Does this PR introduce a user-facing change?

```release-note
Inspecting containers without healthchecks will return nil for heath field.
```

2023-06-06 16:52 UTC, Luap99 commented on libpod/define/container_inspect.go
> +	Health         *HealthCheckResults `json:"Health,omitempty"`
This is part of InspectContainerData which is exposed in pkg/bindings.
We should not break these types as they must be considered stable.

I wonder why omitempty is not working already, AFAIK it doesn't need to be a pointer for that?

2023-06-13 07:28 UTC, vrothberg approved these changes
LGTM
@Luap99 PTAL

2023-06-13 09:29 UTC, Luap99 requested changes

2023-06-13 09:29 UTC, Luap99 commented on test/system/220-healthcheck.bats
> +FailingStreak    | null
ah, I think this might not be a good idea then after all.
If we hide the FailingStreak 0 even when there is a health check we could break parsers.

2023-06-13 09:29 UTC, Luap99 commented on libpod/define/container_inspect.go
> +	FailingStreak int `json:"FailingStreak,omitzero,omitempty"`
omitzero is not needed, please remove it. Only the toml parser uses omitzero.

2023-06-14 08:52 UTC, Luap99 commented
Based on the comments in #18792 I don't think it makes sense to move forward with this. It will not fix the issue reporters problem and likely cause unwanted side effect for the FailingStreak field.
Your original patch of changing this to a pointer makes sense but should wait for podman 5.0 IMO.

2023-06-14 11:19 UTC, closed without merging