API: kill: return 409 on invalid state
containers/podman pull request #19413
Opened 2023-07-28 11:31 UTC by vrothberg

If the container isn't running, make sure to return 409 as specified in the Docker API [1] and the Podman reference.

[1] https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerKill

Fixes: #19368

#### Does this PR introduce a user-facing change?

```release-note
Fix a bug in the containers/kill rest API to correctly return 409 when a container is not running.
```

2023-07-31 07:58 UTC, vrothberg commented
@rhatdan @Luap99 PTAL

2023-07-31 08:10 UTC, Luap99 requested changes

2023-07-31 08:12 UTC, vrothberg commented on pkg/api/handlers/compat/containers.go
> +	logrus.Errorf("COMPAT KILL")
d'oh! thanks

2023-07-31 08:19 UTC, Luap99 approved these changes
LGTM

2023-07-31 09:19 UTC, vrothberg commented on test/apiv2/20-containers.at
> +podman run --replace --name=foo -v /tmp:/tmp $IMAGE true
There's a state check below for exited/stopped, so I went back to using `run` again.  Not sure whether it was a regression test.

2023-07-31 19:33 UTC, rhatdan commented
/lgtm

2023-07-31 19:37 UTC, merged

2023-08-01 07:54 UTC, vrothberg commented
/cherry-pick v4.6