/_ping handler: return OSType http header
containers/podman pull request #19768
Opened 2023-08-28 06:18 UTC by chnrxn

The docker client expects to read the OSType header from the `/_ping` response in order to determine the OS type of the server, for example, when running `docker run --device=/dev/fuse ...`

https://github.com/moby/moby/blob/master/client/ping.go#L57

#### Does this PR introduce a user-facing change?

```release-note

```

2023-08-28 06:43 UTC, flouthoc reviewed
@chnrxn Thanks for the PR, could you please add a test for this as well, a sample test should be somewhere here: https://github.com/containers/podman/blob/main/test/apiv2/01-basic.at, let me know if you need any help :)

2023-08-28 08:04 UTC, chnrxn commented
> @chnrxn Thanks for the PR, could you please add a test for this as well, a sample test should be somewhere here: https://github.com/containers/podman/blob/main/test/apiv2/01-basic.at, let me know if you need any help :)


Hi @flouthoc , does this look ok? I thought of adding the test after the `Method not allowed` section.

```
# Method not allowed
t POST   /_ping                    405
t DELETE /_ping                    405
t POST   libpod/containers/json    405
t POST   libpod/pods/abc           405
t POST   info                      405
t GET    libpod/containers/create  405

# _ping - look for this line in the headers
#   Ostype: linux
t GET ping 200
if grep -qi ^ostype $WORKDIR/curl.headers.out; then
    _show_ok 1 "HTTP-header-OSType=present"
else
    _show_ok 0 "HTTP-header-OSType" "present" "missing"
fi
```

2023-08-28 08:18 UTC, flouthoc commented
Hi @chnrxn , Thanks for looking at this, yes patch LGTM and I can't think of an easier way. Please amend it.

However be prepared to change it when someone other than me takes a looks and suggests a better way. @edsantiago Might be able to suggest a better way.

2023-08-28 10:40 UTC, rhatdan commented
Yes squash your commits.

Tests seem to be blowing up.

2023-08-28 10:44 UTC, chnrxn commented
> Yes squash your commits.
> 
> 
> 
> Tests seem to be blowing up.

Is it possible to Squash on Merge? Or is the repo setup very sensitive to having more than 1 commit?

2023-08-28 10:54 UTC, chnrxn commented
> Tests seem to be blowing up.

Fixed the typo. Hopefully the checks should pass.

2023-08-28 10:56 UTC, flouthoc commented
@chnrxn You can always try running test locally as well https://github.com/containers/podman/blob/main/test/apiv2/README.md

2023-08-28 11:20 UTC, edsantiago requested changes
Thank you for your issue report and PR! Suggestion:
```diff
diff --git a/test/apiv2/01-basic.at b/test/apiv2/01-basic.at
index af080105b..1d8997712 100644
--- a/test/apiv2/01-basic.at
+++ b/test/apiv2/01-basic.at
@@ -12,4 +12,5 @@ t HEAD /libpod/_ping 200
 
 t GET  _ping        200 OK
+like "$(<$WORKDIR/curl.headers.out)" $'.*\nOstype: ' "#19767 - undocumented part of docker API"
 t HEAD _ping        200
 t GET  libpod/_ping 200 OK
```

Eliminates the need for a second ping so far away from the ping tests; makes it clearer why this test line exists; and, on error, dumps the entire headers, making it possible for a human investigator to get clues.

And yes, please squash your commits. `git push --force` is perfectly safe on PRs.

2023-08-28 14:23 UTC, edsantiago commented
Oh, so close! But your git commit message still includes these two lines which detract from the git history:

>Fix typo. “ping” to “_ping”
>condense test

Could you please `git commit --amend`, removed everything after the `Signed-off-by`, and push again? Thank you!

2023-08-28 14:34 UTC, edsantiago approved these changes

2023-08-28 14:34 UTC, edsantiago commented
Thank you!

2023-08-28 14:36 UTC, chnrxn commented
> Thank you!

This is my first time working with this repo. Thanks for your guidance and patience!

2023-08-28 16:48 UTC, edsantiago commented
LGTM but I'd like someone more API-savvy to confirm:
* that header case ("Ostype" vs "OSType") doesn't matter, i.e., that docker follows RFC2616 in the code linked to above;
* that `GOOS` is the correct value and will work with docker;
* whether or not this needs a release note (I would suggest that it does); and
* anything else I may have missed.

2023-08-28 19:00 UTC, TomSweeneyRedHat commented
LGTM
But like @edsantiago I'd like someone with a bit more API savvy to take a look too.

2023-08-29 11:20 UTC, rhatdan commented
/lgtm
Thanks @chnrxn

2023-08-29 11:25 UTC, merged