add compose v2 command to docker alias script
containers/podman pull request #19855
Opened 2023-09-04 14:47 UTC by felipecwb

`docker compose` is a new recommended command line syntax according to [[docker-compose vs docker compose](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose)](https://docs.docker.com/compose/migrate/#docker-compose-vs-docker-compose) 
To be compatible with the new syntax it introduce the executable switch.

#### Does this PR introduce a user-facing change?

```release-note
Added compose alias command to docker-compose or podman-compose in the docker script
```

2023-09-05 07:36 UTC, vrothberg requested changes
Thanks!

I don't think we need that since there is a `podman compose` command now (see https://github.com/containers/podman/blob/main/cmd/podman/compose.go) which does what you are looking for.

2023-09-05 13:39 UTC, baude commented
thanks for your submission , agree with @vrothberg

2023-09-05 13:39 UTC, baude commented
thanks for your submission , agree with @vrothberg

2023-09-05 13:40 UTC, closed without merging

2023-09-09 17:51 UTC, felipecwb commented
thanks for the feedback!