Support size option when creating tmpfs volumes
containers/podman pull request #20451
Opened 2023-10-23 15:26 UTC by rhatdan

Fixes: https://github.com/containers/podman/issues/20449

#### Does this PR introduce a user-facing change?

```release-note
podman volume create supports -opt o=size=XYZ on tmpfs file systems
```

2023-10-23 19:48 UTC, edsantiago requested changes
Test suggestion, and, very confusing wording.

2023-10-23 19:48 UTC, edsantiago commented on test/system/160-volumes.bats
> +    run_podman volume create -o type=tmpfs -o o=size=2M -o device=tmpfs $myvolume
Suggestion: nuke lines 439-441, and replace this block here with:
```bash
    run_podman run --rm -v $myvolume:/vol $IMAGE stat -f -c "%T %b %s" /vol
    read fstype fsblocks fsblocksize <<<"$output"
    assert "$fstype" = "tmpfs" "stat %T - filesystem type"
    assert "$(($fsblocks * $fsblocksize))" == "$((2048 * 1024))" "filesystem size (product of nblocks * blocksize)"
```

2023-10-23 19:48 UTC, edsantiago commented on docs/source/markdown/podman-volume-create.1.md
> +  - The `o` option supports the `size` option to set the maximum size of the created volume, the `inodes` option to set the maximum number of inodes for the volume and `noquota` to completely disable
Sometimes I can forgive a missing Oxford comma, but absolutely not here. Please add one here:
```
...for the volume, and `noquota`
                 ^---- between "volume" and "and"
```

2023-10-23 19:48 UTC, edsantiago commented on docs/source/markdown/podman-volume-create.1.md
> +  The `size` option is supported on "tmpfs" file systems.
I'm having a hard time with this. I find this more understandable, but am not sure if it's correct:
```
The `size` option is supported only on `tmpfs` and `xfs[note]` filesystems.
The `inodes` option is supported only on `xfs[note]`. Any other use will throw an error, maybe, I dunno?
Note: xfs filesystems must be mounted with the `prjquota` flag as described in **xfs_quota(8)**. Podman will throw an error if they're not.
```

2023-10-23 19:54 UTC, mheon commented
Code LGTM

2023-10-24 14:06 UTC, rhatdan commented
@edsantiago @Luap99 @vrothberg @giuseppe @umohnani8 @baude PTAL

2023-10-24 15:07 UTC, vrothberg reviewed
I let @edsantiago give his final blessing

2023-10-24 15:26 UTC, rhatdan commented on docs/source/markdown/podman-volume-create.1.md
> +  Note: xfs filesystems must be mounted with the `prjquota` flag described in the **xfs_quota(8)** man page. Podman will throw an error if they're not.
@umohnani8 is working with this now.

2023-10-24 15:37 UTC, edsantiago approved these changes

2023-10-24 15:40 UTC, merged