systests: cp: add wait_for_ready
containers/podman pull request #20912
Opened 2023-12-05 17:50 UTC by edsantiago

Some of the tests were doing "podman run -d" without wait_for_ready.
This may be the cause of some of the CI flakes. Maybe even all?
It's not clear why the tests have been working reliably for years
under overlay, and only started failing under vfs, but shrug.

Thanks to Chris for making that astute observation.

Fixes: #20282  (I hope)

Signed-off-by: Ed Santiago <santiago@redhat.com>
```release-note
None
```

2023-12-05 18:01 UTC, Luap99 requested changes
sounds like a logical explanation to me but I think you have overdone it a bit.

2023-12-05 18:01 UTC, Luap99 commented on test/system/065-cp.bats
> +    wait_for_ready test-ctr
here

2023-12-05 18:01 UTC, Luap99 commented on test/system/065-cp.bats
> +    wait_for_ready dest-ctr
and here

2023-12-05 18:25 UTC, edsantiago commented
>but I think you have overdone it a bit.

I half-agree. My first pass was addressing only the touch/mkdir containers. After some testing, and some thinking about it, I decided I never want to look at this flake again. I then applied `wait_for_ready` to every `run -d`. Is that harmful?

2023-12-05 18:46 UTC, edsantiago commented
OK. I'll repush once CI finishes.

2023-12-06 10:53 UTC, Luap99 approved these changes
LGTM

2023-12-06 15:35 UTC, rhatdan commented
/lgtm

2023-12-06 15:38 UTC, merged