Allow PublishPorts to be used with [Pod] entry
containers/podman pull request #21039
Opened 2023-12-15 19:40 UTC by rhatdan

Fixed: https://github.com/containers/podman/issues/21035

#### Does this PR introduce a user-facing change?

```release-note
[Pod] quadlets now support PublishPorts.
```

2023-12-17 06:48 UTC, ygalblum approved these changes
LGTM

2023-12-17 06:51 UTC, ygalblum reviewed
Sorry, missed this in my initial review. This is why the tests are failing

2023-12-17 06:51 UTC, ygalblum commented on test/e2e/quadlet/network.pod
> +## assert-podman-args --publish 127.0.0.1:80:90
```suggestion
## assert-podman-pre-args --publish 127.0.0.1:80:90
```

2023-12-17 06:52 UTC, ygalblum requested changes
See my comment on the test

2023-12-17 14:45 UTC, ygalblum approved these changes
LGTM

2023-12-18 12:51 UTC, rhatdan commented
@mheon @Luap99 @baude @ashley-cui @umohnani8 @giuseppe PTAL

2023-12-18 14:25 UTC, ashley-cui reviewed
/hold
/lgtm

2023-12-18 20:27 UTC, rhatdan commented
/unhold

2023-12-18 20:30 UTC, merged