libpod/events: Update event time format and add timeNano
containers/podman pull request #21047
Opened 2023-12-16 17:33 UTC by AhmedGrati

#### Does this PR introduce a user-facing change?

Fixes #14993.

Yes

```release-note
The `Time` field in the output of `podman events --format '{{json .}}'` has been changed to `time`, and its value is now a Unix timestamp in seconds. 
Apart from that, a `timeNano` field is also introduced, which is the same as the time field but in nanoseconds precision.
```

2023-12-16 17:35 UTC, AhmedGrati commented
@vrothberg @rhatdan PTAL.

2023-12-17 11:16 UTC, rhatdan commented
Thanks @AhmedGrati 
You broke some tests.  One issue is this could be a breaking change. I guess it could go into 5.0 though,

@Luap99 @mheon @vrothberg WDYT?

2023-12-17 11:18 UTC, rhatdan commented on libpod/events/events.go
>  	switch e.Type {
Can you do this once before the sitch and then use it in each of the case statements?

timUnix:= time.Unix(0, e.TimeNano)

Also why use this rather then just using

e.Time?

2023-12-17 20:58 UTC, AhmedGrati commented
> You broke some tests.

Yes, going to mark this WIP until I find the root cause.

2023-12-18 08:12 UTC, vrothberg commented
> One issue is this could be a breaking change. 

Yes, that is a breaking change.  I'm OK going forward but I won't find time reviewing; I'll be on PTO starting tomorrow.

2023-12-21 09:09 UTC, AhmedGrati commented
Thanks @edsantiago 👍. It's ready for review now,

2023-12-21 14:59 UTC, rhatdan commented
/approve
LGTM
Thanks @AhmedGrati

2024-01-02 19:21 UTC, rhatdan commented
@mheon @Luap99 @vrothberg @giuseppe @edsantiago PTAL

2024-01-03 10:18 UTC, Luap99 requested changes
We shouldn't change the internal type. This just creates unnecessary breaking changes for API users (which is acceptable due 5.0 but we should keep breaking changes to a minimum and I really do not see the advantage of this for API users). The other problem is that you store two time fields in the log which contain redundant information so this just wastes space. 

The better way to fix this is to have a proper cli frontend struct in cmd/podman/system/events.go that you can convert the libpod event to and then display it only on the cli level.

2024-01-05 15:37 UTC, AhmedGrati commented
@Luap99 okay then, if no objections I'll work on that!

2024-01-10 11:24 UTC, AhmedGrati commented
> The better way to fix this is to have a proper cli frontend struct in cmd/podman/system/events.go that you can convert the libpod event to and then display it only on the cli level.

@Luap99 looking into this, I think we'll need to have duplicate `event` structures. The one already in the `Libpod` API and the other is in the `cmd` level, which means that we'll have some sort of dependencies between these structures where any change made to the `Libpod` event should be reflected in the `cmd` event which can be hard to maintain. please correct me if I'm missing something. wdyt?

2024-01-10 12:32 UTC, Luap99 commented
Yes there is duplication for most of the fields. But this brings in order advantages, having a proper stable cli struct which we then no longer break by accident (hopefully). It also means the we can have different data, for example the internal struct uses one time field while the cli one can use two.

2024-01-16 23:30 UTC, AhmedGrati commented
@Luap99 Can you take a look at this? (Any hint about the issue?)

2024-01-23 11:31 UTC, Luap99 commented
try with

```diff
diff --git a/cmd/podman/system/events.go b/cmd/podman/system/events.go
index d5635599e..ec398ee9d 100644
--- a/cmd/podman/system/events.go
+++ b/cmd/podman/system/events.go
@@ -163,7 +163,7 @@ func eventsFlags(cmd *cobra.Command) {
 
        formatFlagName := "format"
        flags.StringVar(&eventFormat, formatFlagName, "", "format the output using a Go template")
-       _ = cmd.RegisterFlagCompletionFunc(formatFlagName, common.AutocompleteFormat(&events.Event{}))
+       _ = cmd.RegisterFlagCompletionFunc(formatFlagName, common.AutocompleteFormat(&Event{}))
 
        flags.BoolVar(&eventOptions.Stream, "stream", true, "stream events and do not exit when returning the last known event")
```

2024-01-31 14:40 UTC, rhatdan commented
@Luap99 @vrothberg PTAL

2024-02-19 00:12 UTC, rhatdan commented
@AhmedGrati Could you rebase?

2024-02-21 20:56 UTC, AhmedThresh commented
@rhatdan @Luap99 the main account is currently locked... I'll return to work on this once unlocked (hopefully very soon...)

2024-02-22 10:51 UTC, Luap99 commented
I am sorry to hear this. I take it over, rebase and add some small changes. We want to get this in by today.
https://github.com/containers/podman/pull/21784

2024-02-22 10:51 UTC, closed without merging