CI: must-add-tests check: use GH label, not text
containers/podman pull request #21891
Opened 2024-02-29 20:39 UTC by edsantiago

Old way: edit commit message, add magic string, re-push

New way: repo maintainer adds a Github label to PR, hits Rerun

I've looked and looked for the history behind this script
and why I didn't do it this way in the first place. I've
concluded that I just never thought of it.

Signed-off-by: Ed Santiago <santiago@redhat.com>

2024-02-29 20:40 UTC, edsantiago commented
Curious if the sekrit detector will trigger

2024-02-29 20:46 UTC, rhatdan commented
LGTM
Thanks.

2024-03-01 11:34 UTC, Luap99 requested changes
I like it overall.
However this is missing a CONTRIBUTING.md update as it still lists adding `[NO NEW TESTS NEEDED]`

2024-03-01 12:34 UTC, Luap99 approved these changes
LGTM
@containers/podman-maintainers PTAL

2024-03-01 12:38 UTC, vrothberg reviewed
LGTM

Maybe we can combine the two approaches?  The old magic string could lead to auto-apply the label.

2024-03-01 12:38 UTC, vrothberg commented
/lgtm
/hold

2024-03-01 13:40 UTC, merged

2024-03-02 02:35 UTC, edsantiago commented
>Maybe we can combine the two approaches? The old magic string could lead to auto-apply the label.

@vrothberg my understanding, based on discussion in another PR, is that there is some value to requiring repo-maintainer signoff on PRs without tests. At a very minimum it will bubble up to someone's attention, and that someone can suggest ways to test. And hence not require the label.