Fix reference to deprecated types.Info
containers/podman pull request #22163
Opened 2024-03-25 18:24 UTC by baude

upstream docker folks deprecated types.Info in favor of system.Info.

fixes #22132 and #22117

#### Does this PR introduce a user-facing change?

```release-note
None
```

2024-03-25 22:13 UTC, baude commented
the test failure i think is legit ... will look tomorrow.

2024-03-26 15:03 UTC, edsantiago commented
The test failure I see it:
```
AssertionError: 'Container' not found in blah blah
```
The PR, as I read it, removes 'Container'.

The string "Container" appears in  https://github.com/containers/podman/blob/5c39ddca5dc7ac026ba4eacfd271450e7d0c7008/test/apiv2/python/rest_api/test_v2_0_0_image.py#L48

2024-03-26 15:16 UTC, nalind commented
> The test failure I see it:
> 
> ```
> AssertionError: 'Container' not found in blah blah
> ```
> 
> The PR, as I read it, removes 'Container'.
> 
> The string "Container" appears in
> 
> https://github.com/containers/podman/blob/5c39ddca5dc7ac026ba4eacfd271450e7d0c7008/test/apiv2/python/rest_api/test_v2_0_0_image.py#L48

It looks like the "new" Container field needed to be added to the ImageInspect type rather than the Info type.

2024-03-26 19:52 UTC, ashley-cui commented
LGTM

2024-03-26 19:54 UTC, edsantiago requested changes

2024-03-26 19:54 UTC, edsantiago commented on pkg/api/handlers/compat/images.go
> +	fmt.Println(inspect)
debug?

2024-03-26 20:10 UTC, nalind commented on pkg/api/handlers/compat/images.go
> +	return &handlers.ImageInspect{Container: "", ImageInspect: dockerImageInspect}, nil
That's the default value for a string field, so unless there's a reason to be explicitly setting it that I'm missing, it can be omitted.

2024-03-27 17:44 UTC, edsantiago approved these changes

2024-03-27 17:47 UTC, edsantiago commented
LGTM but it's a wee bit more than I can slashlgtm

2024-03-27 21:10 UTC, rhatdan commented
/lgtm

2024-03-27 21:14 UTC, merged

2024-05-28 09:10 UTC, hellt commented
Hi @baude 

there is still entries of docker.Info as of 5.0.3 -- https://github.com/containers/podman/blob/v5.0.3/pkg/api/handlers/types.go#L77