podman exec CID without command should exit 127
containers/podman pull request #22347
Opened 2024-04-11 15:10 UTC by rhatdan

#### Does this PR introduce a user-facing change?

Fixes: 
```release-note

```

2024-04-11 15:23 UTC, edsantiago commented
Thanks, Dan. You'll also need to fix this:
```
diff --git a/test/e2e/exec_test.go b/test/e2e/exec_test.go
index efb9e13ac..9e7b96323 100644
--- a/test/e2e/exec_test.go
+++ b/test/e2e/exec_test.go
@@ -32,7 +32,7 @@ var _ = Describe("Podman exec", func() {
 		// With no command
 		session = podmanTest.Podman([]string{"exec", "test1"})
 		session.WaitWithDefaultTimeout()
-		expectedStatus := 255
+		expectedStatus := 127
 		if IsRemote() {
 			expectedStatus = 125
 		}

```
Any chance you could fix `podman-remote` exit status too?

2024-04-11 15:25 UTC, edsantiago requested changes
I would suggest deleting two of your new tests (which are dups of tests in `basic test`) and moving the new one up to `basic test`.

2024-04-11 15:25 UTC, edsantiago commented on test/system/075-exec.bats
> +    run_podman 127 exec $cid
Ain't gonna pass podman-remote

2024-04-11 15:25 UTC, edsantiago commented on test/system/075-exec.bats
> +    run_podman 126 exec $cid /etc
Already tested way way way at top, line 29, and with special-case code for runc.

2024-04-12 11:13 UTC, rhatdan commented
@edsantiago @Luap99 @baude @mheon @giuseppe This is ready to merge.

2024-04-12 11:44 UTC, rhatdan commented
Ok I will change the commit message, and force commit

2024-04-12 11:44 UTC, rhatdan commented
Sadly I can not force commit.

2024-04-12 11:50 UTC, Luap99 approved these changes
LGTM

2024-04-12 12:12 UTC, mheon commented
/lgtm

2024-04-12 12:51 UTC, merged