Change `defaultmachine` to `activemachineconnection`
containers/podman pull request #23841
Opened 2024-09-03 14:14 UTC by jakecorrenti

Changes the `defaultmachine` field in `podman machine info` to `activemachineconnection`.

The name `defaultmachine` caused confusion around whether the user was able to set a default podman machine via system connections. Regardless of system connections, the default podman machine will always be `podman-machine-default`.

Fixes: #23353

#### Does this PR introduce a user-facing change?

```release-note
The `defaultmachine` field in `podman machine info` now becomes `activemachineconnection`
```

2024-09-03 16:11 UTC, Luap99 requested changes

2024-09-03 16:35 UTC, jakecorrenti commented on pkg/domain/entities/machine.go
> -	DefaultMachine   string `json:"DefaultMachine"`
So would the best course of action here to just make the manpage better and be specific about what `defaultmachine` means?

2024-09-03 17:38 UTC, jakecorrenti commented on pkg/domain/entities/machine.go
> -	DefaultMachine   string `json:"DefaultMachine"`
I avoided adding the field in addition. I feel like it would be confusing what the difference would be, like you said.

2024-09-04 10:12 UTC, Luap99 approved these changes
LGTM

2024-09-04 11:45 UTC, rhatdan commented
/lgtm

2024-09-04 11:48 UTC, merged