Add podman-rootless.7 man page
containers/podman pull request #23875
Opened 2024-09-05 10:28 UTC by rhatdan

This is a follow up to 5389eee7376cf81fbfdaf58cd58d38b287f5da23 to add rooltess.md information to man pages to help users discover solutions to troubleshooting and rooless issues.

Specicifally I was surprised when binding to ports < 1024 was not covered in podman-troubleshooting.7 man page.

#### Does this PR introduce a user-facing change?

```release-note
podman-rootless.7 man page for troubleshooting rootless issues added.
```

2024-09-05 11:59 UTC, edsantiago requested changes
Needs a gitignore fix, otherwise LGTM

2024-09-05 13:52 UTC, edsantiago approved these changes

2024-09-05 13:53 UTC, edsantiago commented
order out of, but since there are no CI checks to enforce that, LGTM

2024-09-05 18:29 UTC, rhatdan commented
@Luap99 @mheon @TomSweeneyRedHat @baude @giuseppe @lsm5 PTAL

2024-09-06 08:49 UTC, Luap99 approved these changes
/lgtm

2024-09-06 08:51 UTC, merged