Checking for multiple registries when login/logout
containers/podman pull request #24888
Opened 2024-12-21 19:14 UTC by lslavkov

Creating a check for `podman login` if there is a multiple registries in the `registry.conf` to avoid any issues where credential getting replaced by `docker login`

Fixes #22400

2024-12-23 14:36 UTC, rhatdan commented
Please rebase and squash your commit.

Thanks for the PR.

2024-12-23 14:36 UTC, rhatdan commented
/approve

2024-12-24 21:37 UTC, lslavkov commented
@rhatdan please review this again. It should be fine now

2024-12-24 21:45 UTC, lslavkov commented
@rhatdan I was able to squash it but my commit description got messed up. Hope that is nothing groundbreaking issue

2025-01-02 16:38 UTC, rhatdan commented
Any chance you could add a test?

2025-01-03 10:21 UTC, lslavkov commented
Could try but no promises.

2025-01-06 08:33 UTC, lslavkov commented
@rhatdan should I create separate file for this test or adding additional test case in `test/e2e/login_logout_test.go`?

2025-01-07 01:24 UTC, mheon commented
@lslavkov Existing login_logout_test file is the preferred place, thanks!

2025-01-07 16:03 UTC, Luap99 requested changes
IMO this is a breaking change and shouldn't be done without a major version. And if we want this then I think it needs to go into c/common so we can make skopeo and buildah match the behavior.

2025-01-07 16:03 UTC, Luap99 commented on cmd/podman/login.go
> +	}
This is a breaking change so we cannot accept this until a 6.0 IMO.
And most importantly this code is broken. You always reject more than one registry even if one was specifed as argument on the cli (in the args array)

Any the login code seem shared between buildah and skopeo as well so if we decide to fix this we should fix this for all in https://github.com/containers/common/blob/main/pkg/auth/auth.go

And if you look into that code you see there is already an AcceptUnspecifiedRegistry option which is quite whay you do here but it we can add another case there for this new behavior.
https://github.com/containers/common/blob/514bf04d8e6a6ac19b71147b534875ca8001785f/pkg/auth/auth.go#L137

2025-01-09 09:42 UTC, lslavkov commented on cmd/podman/login.go
> +	}
So if I understand correctly that `registriesFromFile` is gonna fail regardless if we add which registry we wish to login?

2025-01-19 07:42 UTC, lslavkov commented
/assign

2025-01-24 12:27 UTC, lslavkov commented
@Luap99 should I close this PR and redirect my focus to the c/common?

2025-02-03 09:42 UTC, closed without merging