Container detach message (Docker Consistency)
containers/podman pull request #7953
Opened 2020-10-07 19:01 UTC by ParkerVR

For https://github.com/containers/podman/issues/7751

After a 'docker attach', <ctrl+p> <ctrl+q> detaches with message 'read escape sequence'. This was not occurring for me on 'docker run -it' or 'podman run -it' so I modified the podman behavior so this occurs only on attach as well.

2020-10-07 22:01 UTC, jwhonce requested changes

2020-10-07 22:01 UTC, jwhonce commented on pkg/domain/infra/abi/containers.go
> +				report.Err = errors.Wrapf(err, "Failed to evict container: %q", id)
error elements should start with lowercase not uppercase. If you need this exception for compatibility please add a comment.

2020-10-07 22:01 UTC, jwhonce commented on pkg/domain/infra/abi/containers.go
> +	os.Stdout.WriteString("read escape sequence\n")
I would add a comment why this is happening.

2020-10-07 23:45 UTC, rhatdan commented on pkg/domain/infra/abi/containers.go
> +			return errors.Wrapf(err, "unable to read /proc/self/fd")
Doesn't ioutil give you this information in ReadDir

2020-10-07 23:57 UTC, rhatdan commented on pkg/domain/infra/abi/containers.go
> +			return errors.Wrapf(err, "unable to read /proc/self/fd")
```
package main

import (
	"fmt"
	"io/ioutil"
)

func main() {
	_, err := ioutil.ReadDir("/tmp/missing")
	fmt.Println(err)
}
```
go run /tmp/t.go 
open /tmp/missing: no such file or directory

2020-10-13 19:59 UTC, rhatdan commented
@ParkerVR Needs a rebase.

2020-10-13 21:18 UTC, ParkerVR commented
determined necessary, an alternative method was used (https://github.com/containers/podman/pull/7955)

2020-10-13 21:18 UTC, closed without merging