Add API for communicating with Docker volume plugins
containers/podman pull request #8357
Opened 2020-11-16 19:35 UTC by mheon

Docker provides extensibility through a plugin system, of which several types are available. This provides an initial library API for communicating with one type of plugins, volume plugins. Volume plugins allow for an external service to create and manage a volume on Podman's behalf.

This does not integrate the plugin system into Libpod or Podman yet; that will come in subsequent pull requests.

This replaces #4548 and will begin the continuation of that work.

2020-11-16 19:36 UTC, mheon commented
I'm especially interested from a review from @jwhonce on the HTTP bits.

2020-11-16 19:36 UTC, mheon commented
@rhatdan will also be interested in this.

2020-11-16 19:37 UTC, mheon commented on go.mod
> +	github.com/containers/libpod v1.9.3
Eeek. I don't know how this got in here...

2020-11-16 21:20 UTC, jwhonce reviewed
This is using a seperate HTTP Server from current API server. That is not "bad" but it does imply as written: 
1) people looking at this code need to know this server configuration is not impacted by pkg/api/server, 
2) this is hard-wiring a unix domain socket on the server while the imported library does allow tcp connections

I also didn't catch where the socket is being created/cleaned up

2020-11-16 21:27 UTC, mheon commented
This is not a server, it is a client. The servers are run by individual plugins; we connect to the plugins via Unix socket and speak their REST API when we want them to perform services for us. The lifecycle of their sockets is external to Podman and is the business of the plugin creator.

2020-11-16 21:57 UTC, jwhonce requested changes

2020-11-16 21:57 UTC, jwhonce commented on libpod/plugin/volume_api.go
> +	}
```suggestion
	}
	defer resp.Body.Close()
```

2020-11-16 21:57 UTC, jwhonce commented on libpod/plugin/volume_api.go
> +	}
```suggestion
	}
	defer resp.Body.Close()
```

2020-11-17 01:24 UTC, TomSweeneyRedHat commented on libpod/plugin/volume_api.go
> +		return errors.Wrapf(err, "error unmarshaling plugin %s activation response", newPlugin.Name)
```suggestion
		return errors.Wrapf(err, "error unmarshalling plugin %s activation response", newPlugin.Name)
```

2020-11-17 01:25 UTC, TomSweeneyRedHat commented on libpod/plugin/volume_api.go
> +		return nil, errors.Wrapf(err, "error unmarshaling volume plugin %s list response", p.Name)
```suggestion
		return nil, errors.Wrapf(err, "error unmarshalling volume plugin %s list response", p.Name)
```

2020-11-17 01:26 UTC, TomSweeneyRedHat commented on libpod/plugin/volume_api.go
> +		return nil, errors.Wrapf(err, "error unmarshaling volume plugin %s get response", p.Name)
```suggestion
		return nil, errors.Wrapf(err, "error unmarshalling volume plugin %s get response", p.Name)
```

2020-11-17 01:26 UTC, TomSweeneyRedHat commented on libpod/plugin/volume_api.go
> +		return "", errors.Wrapf(err, "error unmarshaling volume plugin %s path response", p.Name)
```suggestion
		return "", errors.Wrapf(err, "error unmarshalling volume plugin %s path response", p.Name)
```

2020-11-17 01:27 UTC, TomSweeneyRedHat commented on libpod/plugin/volume_api.go
> +		return "", errors.Wrapf(err, "error unmarshaling volume plugin %s path response", p.Name)
```suggestion
		return "", errors.Wrapf(err, "error unmarshalling volume plugin %s path response", p.Name)
```

2020-11-18 18:07 UTC, umohnani8 commented
code LGTM once the suggestions are addressed.

2020-11-18 18:25 UTC, mheon commented
All comments addressed

2020-11-18 23:07 UTC, TomSweeneyRedHat commented
@mheon looks like a gofmt issue with `/libpod/plugin/volume_api.go`

2020-11-19 16:04 UTC, mheon commented
Force-pushed with fix

2020-11-19 20:10 UTC, mheon commented
@containers/podman-maintainers This is ready

2020-11-19 20:46 UTC, rhatdan commented
@mheon I don't think this should go in until we do 3.0.

2020-11-19 20:53 UTC, mheon commented
Sure, probably a good call.

2020-12-01 17:57 UTC, mheon commented
3.0 is landed, this is ready now @containers/podman-maintainers

2020-12-01 19:48 UTC, umohnani8 commented
LGTM @baude @rhatdan PTAL

2020-12-01 21:30 UTC, baude commented
/lgtm

2020-12-01 21:32 UTC, merged