Close the stdin/tty when using podman as a restAPI.
containers/podman pull request #8717
Opened 2020-12-14 15:47 UTC by rhatdan

Currently the service is attempting to prompt on shortname expansion if you run
with a terminal. This change will cause the service to default to no terminal
and not prompt.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

2020-12-14 15:48 UTC, rhatdan commented
Helps fix: https://github.com/containers/podman/issues/8700

2020-12-14 15:48 UTC, rhatdan commented
@mtrmac @vrothberg PTAL

2020-12-14 15:57 UTC, mheon commented
LGTM

2020-12-14 16:12 UTC, Luap99 reviewed
The code does not compile but that is definitely what I want.

2020-12-14 16:14 UTC, vrothberg reviewed
I would be cool to close stdin unconditionally.

Thanks for tackling it, @rhatdan and thanks to @mtrmac for the great idea.

2020-12-14 16:22 UTC, mtrmac requested changes

2020-12-14 22:28 UTC, rhatdan commented on cmd/podman/system/service_abi.go
> +	if !opts.TTY {
I don't believe it is, but I thought @vrothberg had talked about it and was not absolutely sure.  I will just close stdin and be done with it.

2020-12-14 22:45 UTC, mtrmac commented on cmd/podman/system/service_abi.go
> +	if !opts.TTY {
I’m not at all sure about this either (closing FD 0 is the blocker for me), I just don’t much like adding options as the default choice.

2020-12-14 22:45 UTC, mtrmac commented on cmd/podman/system/service_abi.go
> +		os.Stdin.Close()
To clarify, open `/dev/null` and place it in FD 0 instead of the original. (No, I don’t know what’s the idiomatic way to do that in Golang.)

2020-12-15 10:12 UTC, rhatdan commented on cmd/podman/system/service_abi.go
> +		os.Stdin.Close()
The code I have now closes os.Stdin and replaces it with a file pointing to os.DevNull.  This causes the service to do the right thing.  I am not sure if I have to go all the way to the dup2, call.

2020-12-15 10:12 UTC, vrothberg reviewed
LGTM

2020-12-15 10:12 UTC, rhatdan commented on cmd/podman/system/service_abi.go
> +		os.Stdin.Close()
```
+       // Close stdin, so shortnames will not prompt
+       devNullfile, err := os.Open(os.DevNull)
+       if err != nil {
+               return err
+       }
+
+       os.Stdin.Close()
+       os.Stdin = devNullfile
```

2020-12-15 11:46 UTC, mtrmac commented on cmd/podman/system/service_abi.go
> +	devNullfile, err := os.Open(os.DevNull)
This allocates a new Unix FD.

2020-12-15 11:46 UTC, mtrmac commented on cmd/podman/system/service_abi.go
> +	os.Stdin.Close()
This closes Unix FD 0

2020-12-15 11:46 UTC, mtrmac commented on cmd/podman/system/service_abi.go
> +	os.Stdin = devNullfile
This is a Go pointer assignment that AFAICS does nothing with UNIX FDs, FD 0 remains closed and will be reused.

2020-12-15 15:43 UTC, rhatdan commented
@mtrmac Ok, now I am using unix.Dup2 and looking at the process fds, 
ls -l /proc/373817/fd/0
lr-x------. 1 dwalsh dwalsh 64 Dec 15 10:42 /proc/373817/fd/0 -> /dev/null

2020-12-15 16:23 UTC, mtrmac reviewed
LGTM. (I’m not going to worry about flushing buffers…)

2020-12-15 16:24 UTC, mtrmac approved these changes

2020-12-15 16:50 UTC, mheon commented
LGTM

2020-12-15 22:23 UTC, TomSweeneyRedHat commented
LGTM
but `EXT. services` test is failing which is new to me.  I don't think it's related to the change, but I'm not sure.

2020-12-15 22:32 UTC, edsantiago commented
Ext. services: you'll need to rebase, sorry. See https://github.com/containers/podman/pull/8726#issuecomment-745482940 for context

2020-12-16 20:11 UTC, rhatdan commented
/hold

2020-12-17 14:06 UTC, rhatdan commented
/hold cancel

2020-12-17 14:09 UTC, merged