[v3.0] [CI:DOCS] Cirrus: Fix running Validate task on branches
containers/podman pull request #9062
Opened 2021-01-21 20:31 UTC by cevich

Followup to 4c60523

For whatever reason Cirrus-CI does not set `$CIRRUS_BASE_SHA` when
testing on a branch or tag.  If the branch happened to also not have
any successful previous runs, then `$EPOCH_TEST_COMMIT` was being set
to the error-flagging value `YOU_FOUND_A_BUG`.

Fix this by detecting an empty value when running on a branch or via
`hack/get_ci_vm.sh` (`$CIRRUS_TAG` will be empty) and setting
`$CIRRUS_BASE_SHA` based on the upstream branch HEAD.  Otherwise,
instead of using `YOU_FOUND_A_BUG`, simply reference the HEAD commit.

Also, simplify the smoke & validate tasks so they do not duplicate
running `contrib/cirrus/pr-should-include-tests` (i.e. `tests-included`
target).

Signed-off-by: Chris Evich <cevich@redhat.com>

2021-01-22 09:56 UTC, rhatdan commented
LGTM
@edsantiago PTAL
@containers/podman-maintainers PTAL

2021-01-22 17:08 UTC, QiWang19 reviewed
LGTM

2021-01-22 17:09 UTC, edsantiago requested changes
Same feedback as #9063. This must not merge as-is.

2021-01-22 17:38 UTC, rhatdan commented
I would prefer to merge the main branch patch, once @edsantiago comments are addressed and then cherry-pick the fix to the 3.0 branch.

2021-01-22 17:38 UTC, closed without merging

2021-01-25 19:36 UTC, cevich commented
> then cherry-pick the fix to the 3.0 branch.

okay, will do.