Support label type dict on compat build
containers/podman pull request #9550
Opened 2021-03-01 14:45 UTC by baude

The compatibility endpoint for build labels should be of type dict (not
list).  For backwards compatibility, we support both.

Fixes: #9517

Signed-off-by: baude <bbaude@redhat.com>

2021-03-01 14:52 UTC, rhatdan commented
LGTM

2021-03-01 17:37 UTC, TristanCacqueray commented on test/python/docker/test_images.py
> +            self.assertEqual(image.labels["grape"], labels["green"])
Shouldn't this use `labels["grape"]` in the second argument of assertEqual?

2021-03-01 18:26 UTC, jwhonce requested changes
Note my PR is going to mess with your paths.

2021-03-01 18:26 UTC, jwhonce commented on test/python/docker/test_images.py
> +            self.assertEqual(image.labels["grape"], labels["grape"])
```suggestion
            self.assertListEqual(image.labels, labels)
```
Provides better diagnostics

2021-03-01 19:19 UTC, baude commented
> Note my PR is going to mess with your paths.

can you elaborate @jwhonce

2021-03-04 13:23 UTC, baude commented
merge me

2021-03-04 16:08 UTC, mheon commented
/lgtm

2021-03-04 16:09 UTC, merged